// AUTO-GENERATED from styles.css `.aos-root` by scripts/gen-tokens.mjs — DO NOT EDIT.
// Regenerate: npm run gen:tokens
export const TOKENS = {
  amber: "#ffb454",
  bg: "#0a0e14",
  border: "#1f2933",
  chart1: "#00d4ff",
  chart2: "#ff66c4",
  chart3: "#ffc800",
  chart4: "#7afc7a",
  chart5: "#a78bfa",
  chart6: "#ff8a4c",
  chart7: "#94a3b8",
  cyan: "#00d4ff",
  dim: "#6b7d8c",
  green: "#5ee2a0",
  mono: "'Berkeley Mono', 'JetBrains Mono', 'SF Mono', 'Menlo', 'Consolas', monospace",
  panel: "#11161d",
  rose: "#ff5e7e",
  termBackground: "#0a0e14",
  termBlack: "#0a0e14",
  termBlue: "#00d4ff",
  termBrightBlack: "#6b7d8c",
  termBrightBlue: "#5be0ff",
  termBrightCyan: "#a3eaff",
  termBrightGreen: "#7feeb3",
  termBrightMagenta: "#dba8ff",
  termBrightRed: "#ff7a93",
  termBrightWhite: "#e3eef5",
  termBrightYellow: "#ffc97a",
  termCursor: "#00d4ff",
  termCursorAccent: "#0a0e14",
  termCyan: "#7fdbff",
  termForeground: "#c5d6e0",
  termGreen: "#5ee2a0",
  termMagenta: "#c792ea",
  termRed: "#ff5e7e",
  termSelectionBackground: "rgba(0,212,255,0.25)",
  termWhite: "#c5d6e0",
  termYellow: "#ffb454",
  text: "#c5d6e0",
} as const;
export type TokenName = keyof typeof TOKENS;
