#!/bin/sh
# Codex-host rehearsal: a fresh HOME, Claude config dir and Codex home, `aos init --host codex` with the fake
# codex CLI and NO claude, then the written hook commands run for real (SessionStart conventions, Stop `{}`),
# doctor, and uninstall --keep-vault. Needs: node >= 20 and npm on PATH, network for `npm install` inside
# the vendored runtime. Run from anywhere: sh cli/rehearsal/codex-host.sh
set -eu
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
TMP=$(mktemp -d)
export HOME="$TMP/home" CLAUDE_CONFIG_DIR="$TMP/cfg" CODEX_HOME="$TMP/codex"
mkdir -p "$HOME" "$CLAUDE_CONFIG_DIR" "$CODEX_HOME"
printf 'model = "fake-model"\n' > "$CODEX_HOME/config.toml"
export AOS_NO_CLAUDE=1 AOS_CODEX_BIN="$ROOT/cli/fixtures/fake-codex.sh" FAKE_CODEX_LOG="$TMP/codex.log" FAKE_CODEX_STATE="$TMP/codex-mcp.state"
unset AOS_VAULT BRAIN_VAULT AOS_CONFIG CLAUDE_PROJECT_DIR AOS_HOST AOS_NO_CODEX || true
VAULT="$TMP/aos"
SKILLS="$HOME/.agents/skills"

echo "== init --host codex (no claude on this machine)"
node "$ROOT/cli/aos.js" init --host codex --vault "$VAULT" --no-obsidian --provider none --persona-json "$ROOT/cli/fixtures/persona.json" --yes

echo "== what init wrote"
[ -f "$CODEX_HOME/hooks.json" ]
node -e '
const d = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
const ev = Object.keys(d.hooks);
if (ev.join(",") !== "SessionStart,UserPromptSubmit,PostToolUse,Stop,SessionEnd") throw new Error("events: " + ev);
for (const e of ev) for (const g of d.hooks[e]) for (const h of g.hooks) if (!/^env AOS_HOST=codex /.test(h.command)) throw new Error("foreign command: " + h.command);
for (const g of d.hooks.SessionEnd) for (const h of g.hooks) if (h.timeout !== 3) throw new Error("SessionEnd timeout " + h.timeout);
' "$CODEX_HOME/hooks.json"
grep -q '^mcp add agenticos --env AOS_CONFIG=' "$FAKE_CODEX_LOG"
[ -f "$FAKE_CODEX_STATE" ]
[ -f "$SKILLS/wrap/SKILL.md" ] && [ -f "$SKILLS/remember/SKILL.md" ] && [ -f "$SKILLS/recall/SKILL.md" ]
! grep -q 'CLAUDE_PLUGIN_ROOT' "$SKILLS/wrap/SKILL.md"
grep -q 'mcp__agenticos__wrap_session' "$SKILLS/wrap/SKILL.md"
grep -q 'generated by `aos init --host codex`' "$SKILLS/remember/SKILL.md"
node -e '
const c = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
if (!c.hosts || c.hosts.codex.enabled !== true || c.hosts.claude.enabled !== false) throw new Error("hosts: " + JSON.stringify(c.hosts));
if (!c.hosts.codex.bin) throw new Error("codex bin not recorded");
' "$CLAUDE_CONFIG_DIR/agenticos.json"
[ ! -e "$CLAUDE_CONFIG_DIR/plugins" ] || { echo "the Claude plugin path was touched on a codex-only install"; exit 1; }

echo "== the written hook commands run for real"
CMD=$(node -e 'const d=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")); const h=d.hooks.SessionStart.flatMap(g=>g.hooks).find(h=>/inject-conventions$/.test(h.command)); process.stdout.write(h.command)' "$CODEX_HOME/hooks.json")
echo '{"session_id":"reh-1","hook_event_name":"SessionStart","source":"startup"}' | sh -c "$CMD" | grep -q '<agenticos-conventions>'
STOP=$(node -e 'const d=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")); const h=d.hooks.Stop.flatMap(g=>g.hooks).find(h=>/update-session$/.test(h.command)); process.stdout.write(h.command)' "$CODEX_HOME/hooks.json")
OUT=$(echo '{"session_id":"reh-1","hook_event_name":"Stop","stop_hook_active":false}' | sh -c "$STOP")
[ "$OUT" = "{}" ] || { echo "Stop hook printed [$OUT], expected {}"; exit 1; }
PROMPT=$(node -e 'const d=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")); process.stdout.write(d.hooks.UserPromptSubmit[0].hooks[0].command)' "$CODEX_HOME/hooks.json")
echo '{"session_id":"reh-2","hook_event_name":"UserPromptSubmit","prompt":"hi"}' | sh -c "$PROMPT" | grep -q '<brain-context>'

echo "== doctor (codex rows, no claude rows)"
DOC=$(node "$ROOT/cli/aos.js" doctor)
echo "$DOC"
echo "$DOC" | grep -q '^ok    codex CLI'
echo "$DOC" | grep -q '^ok    codex login'
echo "$DOC" | grep -q '^ok    codex hooks'
echo "$DOC" | grep -q '^ok    codex MCP declared'
echo "$DOC" | grep -q '^ok    codex skills'
echo "$DOC" | grep -q '^ok    persona runner *codex'
echo "$DOC" | grep -q '^ok    routines runner *codex'
echo "$DOC" | grep -q 'all checks passed'
! echo "$DOC" | grep -q 'claude CLI'
! echo "$DOC" | grep -q 'plugin installed'

echo "== a persona duty runs through codex exec (dry-run)"
if [ -f "$VAULT/persona/duties/sitrep.md" ]; then
  DRY=$(sh "$VAULT/brain/scripts/persona/run-duty.sh" sitrep --dry-run)
  echo "$DRY" | head -1 | grep -q 'fake-codex.sh$'
  echo "$DRY" | grep -q '^workspace-write$'
  ! echo "$DRY" | grep -q -- '--max-budget-usd'
else
  echo "   (no sitrep duty in this vault; skipped)"
fi

echo "== status names the codex host"
STATUS=$(node "$ROOT/cli/aos.js" status)
echo "$STATUS" | grep -q '^codex '
echo "$STATUS" | grep -q '^hosts      codex$'

echo "== uninstall --keep-vault reverses the codex wiring"
node "$ROOT/cli/aos.js" uninstall --keep-vault --yes
[ ! -e "$CODEX_HOME/hooks.json" ]
[ ! -e "$SKILLS/wrap" ] && [ ! -e "$SKILLS/remember" ]
grep -q '^mcp remove agenticos$' "$FAKE_CODEX_LOG"
[ ! -e "$FAKE_CODEX_STATE" ]
[ -f "$VAULT/MEMORY.md" ]
[ ! -e "$CLAUDE_CONFIG_DIR/agenticos.json" ]
echo REHEARSAL-OK
