const path = require('path');
const os = require('os');
const { VAULT, PATHS, safeStat, listDir, exists, readJson, readText } = require('./util');

// The sidecar lib/skills.js writes into every skill it mirrors from the other host (spec 2026-09-23-universal-skills D8):
// a mirror is the other host's skill, so counting it here would count every universal skill twice.
const MIRROR_SIDECAR = '.aos-mirror.json';

function classifyGsd(names) {
  let gsd = 0;
  const custom = [];
  for (const n of names) {
    if (n.startsWith('gsd-') || n.startsWith('gsd_')) gsd++;
    else custom.push(n);
  }
  return { gsd, custom };
}

/**
 * Codex's own inventory when it is a host (spec 2026-09-23-codex-parity-gaps D9): user skills under ~/.agents/skills
 * (not the ones `aos init --host codex` generated), custom prompts under <codex home>/prompts and the hook entries in
 * <codex home>/hooks.json. null when Codex is not a host. opts.userConfig / codexHome / agentsSkillsDir: test seams.
 */
function codexCapabilities(opts = {}) {
  try {
    const H = require('../lib/host.js');
    const cfg = opts.userConfig !== undefined ? opts.userConfig : require('../lib/paths.js').readUserConfig();
    if (!H.enabledHosts(cfg).includes('codex')) return null;
    const home = opts.codexHome || H.hostDirs('codex', { userConfig: cfg }).configDir;
    const skillsDir = opts.agentsSkillsDir || path.join(os.homedir(), '.agents', 'skills');
    const skills = listDir(skillsDir).filter((d) => {
      const md = path.join(skillsDir, d, 'SKILL.md');
      return exists(md) && !exists(path.join(skillsDir, d, MIRROR_SIDECAR)) && !String(readText(md) || '').includes('generated by `aos init --host codex`');
    }).length;
    const prompts = listDir(path.join(home, 'prompts')).filter((f) => f.endsWith('.md')).length;
    const doc = readJson(path.join(home, 'hooks.json')) || {};
    const hooks = Object.values(doc.hooks || {}).reduce((n, groups) => n + (Array.isArray(groups)
      ? groups.reduce((m, g) => m + (g && Array.isArray(g.hooks) ? g.hooks.length : 0), 0) : 0), 0);
    return { skills, prompts, hooks };
  } catch { return null; }
}

/** opts.vault / opts.claudeConfigDir default to the resolved vault and Claude config dir (they differ in a dedicated vault). */
function collectCapabilities(opts = {}) {
  const vault = opts.vault || VAULT;
  const configDir = opts.claudeConfigDir || PATHS.CLAUDE_CONFIG_DIR;
  const out = {};

  // agents/*.md
  const agentsDir = path.join(configDir, 'agents');
  const agentFiles = listDir(agentsDir).filter(n => n.endsWith('.md'));
  const agentBases = agentFiles.map(n => n.replace(/\.md$/, ''));
  const agentsClass = classifyGsd(agentBases);
  out.agents = {
    count: agentFiles.length,
    gsd: agentsClass.gsd,
    custom: agentsClass.custom,
    totalBytes: agentFiles.reduce((acc, n) => acc + (safeStat(path.join(agentsDir, n))?.size || 0), 0),
  };

  // commands/*.md
  const commandsDir = path.join(configDir, 'commands');
  const commandFiles = listDir(commandsDir).filter(n => n.endsWith('.md'));
  out.commands = {
    count: commandFiles.length,
    names: commandFiles.map(n => n.replace(/\.md$/, '')).sort(),
  };

  // skills/*/ — each should contain SKILL.md
  const skillsDir = path.join(configDir, 'skills');
  const skillDirs = listDir(skillsDir).filter(n => safeStat(path.join(skillsDir, n))?.isDirectory() && !exists(path.join(skillsDir, n, MIRROR_SIDECAR)));
  const missingSkillMd = [];
  for (const d of skillDirs) {
    if (!exists(path.join(skillsDir, d, 'SKILL.md'))) missingSkillMd.push(d);
  }
  const skillsClass = classifyGsd(skillDirs);
  out.skills = {
    count: skillDirs.length,
    gsd: skillsClass.gsd,
    customCount: skillsClass.custom.length,
    custom: skillsClass.custom,
    missingSkillMd,
  };

  // hooks/*.{js,sh}
  const hooksDir = path.join(configDir, 'hooks');
  const hookFiles = listDir(hooksDir).filter(n => /\.(js|sh|ps1)$/.test(n));
  const settings = readJson(path.join(configDir, 'settings.json')) || {};
  const referencedScripts = new Set();
  const HOME = process.env.HOME || os.homedir() || '';
  // Expand env-var home references so paths like "$HOME/.claude/hooks/x.sh"
  // resolve to a real on-disk path instead of being harvested as "/.claude/...".
  const expandHome = (s) => String(s || '')
    .replace(/\$\{HOME\}/g, HOME)
    .replace(/\$HOME\b/g, HOME)
    .replace(/(^|[\s"'=])~(?=\/)/g, `$1${HOME}`);
  const harvestPaths = (cmd) => {
    const matches = expandHome(cmd).match(/(?:[A-Za-z]:[\/\\]|\/)[^\s"']+/g) || [];
    for (const m of matches) referencedScripts.add(path.normalize(m).replace(/\\/g, '/'));
  };
  const settingsHooks = settings.hooks || {};
  for (const event of Object.keys(settingsHooks)) {
    for (const m of (settingsHooks[event] || [])) {
      for (const h of (m.hooks || [])) harvestPaths(h.command);
    }
  }
  if (settings.statusLine?.command) harvestPaths(settings.statusLine.command);
  const hookPathsPresent = hookFiles.map(n => path.join(hooksDir, n).replace(/\\/g, '/'));
  const wired = hookFiles.filter(n => {
    const full = path.join(hooksDir, n).replace(/\\/g, '/');
    for (const ref of referencedScripts) {
      if (ref.toLowerCase() === full.toLowerCase()) return true;
    }
    return false;
  });
  const allUnwired = hookFiles.filter(n => !wired.includes(n));
  // Split unwired into (a) acknowledged-intentional (suppressed via config) and
  // (b) genuinely unexpected orphans that should fire a warning.
  const scannerCfg = readJson(path.join(vault, 'brain/_index/scanner-config.json')) || {};
  const allowedOrphanSet = new Set(scannerCfg.allowedOrphanHooks || []);
  const acknowledgedOrphans = allUnwired.filter(n => allowedOrphanSet.has(n));
  const orphans = allUnwired.filter(n => !allowedOrphanSet.has(n));
  const missingRefs = [];
  for (const ref of referencedScripts) {
    if (!exists(ref)) missingRefs.push(ref);
  }
  out.hooks = {
    count: hookFiles.length,
    wired: wired.length,
    orphans,
    acknowledgedOrphans,
    missingRefs,
    settingsReferenced: referencedScripts.size,
  };

  // brain/scripts/*
  const bScriptsDir = path.join(vault, 'brain/scripts');
  const bScripts = listDir(bScriptsDir).filter(n => /\.(js|sh|ps1)$/.test(n));
  const bWired = bScripts.filter(n => {
    const full = path.join(bScriptsDir, n).replace(/\\/g, '/');
    for (const ref of referencedScripts) {
      if (ref.toLowerCase() === full.toLowerCase()) return true;
    }
    return false;
  });
  out.brainScripts = {
    count: bScripts.length,
    names: bScripts,
    wired: bWired.length,
  };

  // plugins/ top-level
  const pluginsDir = path.join(configDir, 'plugins');
  out.pluginsTopLevel = {
    present: exists(pluginsDir),
    count: listDir(pluginsDir).length,
  };

  out.codex = codexCapabilities(opts);
  return out;
}

module.exports = { collectCapabilities, codexCapabilities };
