#!/usr/bin/env node
/**
 * scan-vault.js — full-coverage scanner for .claude
 *
 * Orchestrates collectors, writes:
 *   brain/_index/snapshot.json   canonical machine-readable
 *   brain/_index/snapshot.md     human-readable with frontmatter (Dataview-queryable)
 *
 * Flags: --json (print snapshot JSON to stdout and skip file writes)
 *        --quiet (no stdout summary)
 */

const { PATHS } = require('./lib/hook-entry.js').hookEntry();
const fs = require('fs');
const path = require('path');

const { VAULT, nowIso, humanSize } = require('./collectors/util');
const { withReport } = require('./lib/pipeline-report.js');
const { collectConfig } = require('./collectors/config');
const { collectCapabilities } = require('./collectors/capabilities');
const { collectFolderAtlas } = require('./collectors/folderAtlas');
const { collectBrain } = require('./collectors/brain');
const { collectProjects } = require('./collectors/projects');
const { collectPlans } = require('./collectors/plans');
const { collectRuntime } = require('./collectors/runtime');
const { collectGsd } = require('./collectors/gsd');
const { collectHealth, renderHealthMarkdown } = require('./collectors/health');
const { collectHistory, writeDailyRecord, prune } = require('./collectors/history');
const { sweepOrphans } = require('./sweep-orphans');
const { collectWorkspaces } = require('./collectors/workspaces');
const { collectHostSessions, attachSessions } = require('./collectors/hostSessions');
const { generateInsight } = require('./collectors/workspaceInsights');
const { withLock } = require('./lib/snapshotLock');
const { collectFileMaps } = require('./collectors/fileMap.js');
const { loadConfig } = require('./lib/config.js');
const { getProvider } = require('./sdk/lib/provider.js');

function readPrevSnapshot() {
  try {
    const p = path.join(VAULT, 'brain/_index/snapshot.json');
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch { return null; }
}

function scan() {
  const start = Date.now();
  const prev = readPrevSnapshot();
  const maintenance = { orphanSweep: sweepOrphans() };
  const snapshot = {
    scannedAt: nowIso(),
    vault: VAULT,
    scanVersion: 6,
    elapsedMs: null,
    maintenance,
    config: collectConfig(),
    capabilities: collectCapabilities(),
    brain: collectBrain(),
    projects: collectProjects(),
    plans: collectPlans(),
    runtime: collectRuntime(),
    gsd: collectGsd(),
    folderAtlas: collectFolderAtlas(),
  };
  snapshot.workspaces = collectWorkspaces({ prevWorkspaces: prev && prev.workspaces ? prev.workspaces : [] });
  // Both hosts' sessions, pinned to the workspace they ran in (workspace hub D2); the rest is what runs outside workspaces/.
  const hostSessions = collectHostSessions();
  snapshot.hostSessions = {
    byCwd: hostSessions.byCwd,
    scannedAt: hostSessions.scannedAt,
    outsideWorkspaces: attachSessions(snapshot.workspaces, hostSessions.byCwd),
  };
  snapshot.health = collectHealth(snapshot);
  snapshot.history = collectHistory(snapshot);
  snapshot.elapsedMs = Date.now() - start;
  return snapshot;
}

function renderMarkdown(s) {
  const lines = [];
  lines.push('---');
  lines.push('type: snapshot');
  lines.push(`scanned: ${s.scannedAt}`);
  lines.push(`elapsed_ms: ${s.elapsedMs}`);
  lines.push('tags: [snapshot, dashboard]');
  lines.push('---');
  lines.push('');
  lines.push('# .claude Snapshot');
  lines.push('');
  lines.push(`> Generated by \`brain/scripts/scan-vault.js\` at ${s.scannedAt} (${s.elapsedMs}ms)`);
  lines.push('');

  // Config
  const c = s.config;
  lines.push('## System Pulse');
  lines.push('');
  if (c.settings?.missing) {
    lines.push('- **settings.json**: MISSING');
  } else {
    const ss = c.settings;
    lines.push(`- **Model**: \`${ss.model}\`  ·  **Effort**: ${ss.effortLevel || '—'}  ·  **Theme**: ${ss.theme || '—'}`);
    lines.push(`- **Hooks wired**: ${ss.hookCount} across events: ${ss.hookEvents.join(', ') || 'none'}`);
    lines.push(`- **Permissions**: ${ss.permissionsAllow} allow-rules  ·  defaultMode=\`${ss.permissionsDefaultMode}\`  ·  dangerous=${ss.dangerousMode}`);
    lines.push(`- **Status line**: \`${ss.statusLine || '—'}\``);
  }
  lines.push(`- **CLAUDE.md**: ${c.claudeMd.missing ? 'MISSING' : `${humanSize(c.claudeMd.size)}, ${c.claudeMd.lines} lines`}`);
  lines.push(`- **MEMORY.md**: ${c.memoryMd.missing ? 'MISSING' : `${c.memoryMd.pointers} pointers`}`);
  lines.push(`- **history.jsonl**: ${c.historyJsonl.missing ? 'MISSING' : `${c.historyJsonl.lines} entries`}`);
  lines.push(`- **GSD manifest**: ${c.gsdManifest.present ? `${c.gsdManifest.fileCount} files` : 'absent'}`);
  if (c.stray.length) lines.push(`- **Stray files**: ${c.stray.join(', ')}`);
  lines.push('');

  // Capabilities
  const cap = s.capabilities;
  lines.push('## Capabilities');
  lines.push('');
  lines.push('| Surface | Count | Notes |');
  lines.push('|---|---|---|');
  lines.push(`| Agents | ${cap.agents.count} | ${cap.agents.gsd} GSD, ${cap.agents.custom.length} custom: ${cap.agents.custom.join(', ') || '—'} |`);
  lines.push(`| Commands | ${cap.commands.count} | ${cap.commands.names.join(', ')} |`);
  lines.push(`| Skills | ${cap.skills.count} | ${cap.skills.gsd} GSD, ${cap.skills.customCount} custom${cap.skills.missingSkillMd.length ? ` · ${cap.skills.missingSkillMd.length} missing SKILL.md` : ''} |`);
  lines.push(`| Hooks | ${cap.hooks.count} | ${cap.hooks.wired} wired, ${cap.hooks.orphans.length} orphan${cap.hooks.missingRefs.length ? ` · ${cap.hooks.missingRefs.length} broken refs` : ''} |`);
  lines.push(`| Brain scripts | ${cap.brainScripts.count} | ${cap.brainScripts.wired} wired: ${cap.brainScripts.names.join(', ')} |`);
  lines.push(`| Plugins (top) | ${cap.pluginsTopLevel.count} | ${cap.pluginsTopLevel.present ? 'dir present' : 'dir absent'} |`);
  if (cap.skills.missingSkillMd.length) {
    lines.push('');
    lines.push(`**Skills missing SKILL.md**: ${cap.skills.missingSkillMd.join(', ')}`);
  }
  if (cap.hooks.orphans.length) {
    lines.push('');
    lines.push(`**Orphan hook scripts** (not referenced in settings.json): ${cap.hooks.orphans.join(', ')}`);
  }
  if (cap.hooks.missingRefs.length) {
    lines.push('');
    lines.push('**Broken hook refs in settings.json**:');
    for (const r of cap.hooks.missingRefs) lines.push(`- \`${r}\``);
  }
  lines.push('');

  // Brain & Memory
  const b = s.brain;
  lines.push('## Brain & Memory');
  lines.push('');
  const mb = b.counts.memoryByType;
  lines.push('| Area | Count | Notes |');
  lines.push('|---|---|---|');
  lines.push(`| Memory | ${b.counts.memoryTotal} | user ${mb.user} · feedback ${mb.feedback} · projects ${mb.projects} · reference ${mb.reference} |`);
  lines.push(`| Patterns | ${b.counts.patterns} | |`);
  lines.push(`| Reflections | ${b.counts.reflections} | latest: ${b.reflectionsLatest || '—'} |`);
  lines.push(`| Sessions | ${b.counts.sessions} | latest: ${b.sessions.latestDate || '—'} · streak: ${b.sessions.streak} · today: ${b.sessions.todayPresent ? 'present' : '**missing**'} |`);
  lines.push(`| Templates | ${b.counts.templates} | ${b.templates.join(', ')} |`);
  lines.push(`| Index files | ${[b.indexFiles.brainMd, b.indexFiles.sessionMd, b.indexFiles.dashboardMd].filter(x => x.present).length}/3 | BRAIN.md ${b.indexFiles.brainMd.present ? `(${b.indexFiles.brainMd.ageDays}d)` : 'missing'} · SESSION.md ${b.indexFiles.sessionMd.present ? `(${b.indexFiles.sessionMd.ageDays}d)` : 'missing'} · DASHBOARD.md ${b.indexFiles.dashboardMd.present ? `(${b.indexFiles.dashboardMd.ageDays}d)` : 'missing'} |`);
  if (b.indexFiles.bases.length) lines.push(`| Obsidian Bases | ${b.indexFiles.bases.length} | ${b.indexFiles.bases.join(', ')} |`);
  lines.push('');

  // Memory health
  const mi = b.memoryIndex;
  lines.push('### Memory Health');
  lines.push('');
  lines.push(`- **MEMORY.md pointers**: ${mi.pointerCount}`);
  if (mi.brokenPointers.length) {
    lines.push(`- **Broken pointers** (${mi.brokenPointers.length}):`);
    for (const p of mi.brokenPointers) lines.push(`  - "${p.title}" → \`${p.target}\``);
  } else {
    lines.push('- **Broken pointers**: none');
  }
  if (mi.orphanMemories.length) {
    lines.push(`- **Orphan memory files** (not in MEMORY.md, ${mi.orphanMemories.length}):`);
    for (const p of mi.orphanMemories) lines.push(`  - \`${p}\``);
  } else {
    lines.push('- **Orphan memories**: none');
  }
  if (mi.orphanPatterns.length) {
    lines.push(`- **Orphan patterns** (${mi.orphanPatterns.length}):`);
    for (const p of mi.orphanPatterns) lines.push(`  - \`${p}\``);
  }
  if (b.oldestMemories.length) {
    lines.push(`- **Oldest memories** (top 3 by age):`);
    for (const o of b.oldestMemories) lines.push(`  - \`${o.path}\` — ${o.ageDays}d old`);
  }
  lines.push('');

  // Projects & Sessions
  const pj = s.projects;
  lines.push('## Projects & Sessions');
  lines.push('');
  lines.push(`**Summary**: ${pj.summary.totalProjects} projects (${pj.summary.runtimeCwdProjects} runtime-cwd, ${pj.summary.userNamedProjects} user-named) · ${pj.summary.totalSessions} sessions · ${humanSize(pj.summary.totalJsonlBytes)} conversation data · ${pj.summary.totalRecords} JSONL records · ${pj.activeSessionCount} active (locked), ${pj.staleSessionCount} stale (≥30d)`);
  lines.push('');

  lines.push('### Projects');
  lines.push('');
  lines.push('| Name | Kind | Size | Sessions | Last activity | Notes |');
  lines.push('|---|---|---|---|---|---|');
  for (const p of pj.projects) {
    if (p.kind === 'runtime-cwd') {
      lines.push(`| \`${p.name}\` | runtime-cwd → \`${p.decodedCwd}\` | ${humanSize(p.totalBytes)} | ${p.jsonlCount} | ${p.latestMtime ? p.latestAgeDays + 'd ago' : '—'} | |`);
    } else {
      const notes = [];
      if (p.hasClaudeMd) notes.push('CLAUDE.md');
      if (p.hasReadme) notes.push('README');
      if (p.linkedMemory) notes.push(`↔ \`${p.linkedMemory}\``);
      else notes.push('**no brain memory**');
      lines.push(`| \`${p.name}\` | user-named | ${humanSize(p.totalBytes)} | ${p.fileCount} files | ${p.ageDays}d ago | ${notes.join(' · ')} |`);
    }
  }
  lines.push('');

  lines.push('### Session Cross-Ref (by UUID)');
  lines.push('');
  lines.push('| UUID (short) | Project | Records | JSONL | Tasks | Env | FileHist | Lock | Last | Status |');
  lines.push('|---|---|---|---|---|---|---|---|---|---|');
  for (const sess of pj.sessions) {
    const short = sess.uuid.slice(0, 8);
    const project = sess.projectName ? `\`${sess.projectName.slice(0, 20)}${sess.projectName.length > 20 ? '…' : ''}\`` : '—';
    const recs = sess.records != null ? sess.records : '—';
    const jBytes = sess.jsonlBytes != null ? humanSize(sess.jsonlBytes) : '—';
    const tasks = sess.hasTasks ? 'yes' : '—';
    const env = sess.hasEnv ? humanSize(sess.envBytes || 0) : '—';
    const fh = sess.hasFileHistory ? humanSize(sess.fileHistoryBytes || 0) : '—';
    const lock = sess.hasLock ? '**LOCK**' : '—';
    const last = sess.ageDays != null ? `${sess.ageDays}d ago` : '—';
    const status = sess.hasLock ? 'active' : sess.stale ? '**stale**' : sess.hasJsonl ? 'ok' : '**orphan**';
    lines.push(`| \`${short}\` | ${project} | ${recs} | ${jBytes} | ${tasks} | ${env} | ${fh} | ${lock} | ${last} | ${status} |`);
  }
  lines.push('');

  if (pj.orphanUuids.sessionEnv.length || pj.orphanUuids.tasks.length || pj.orphanUuids.fileHistory.length) {
    lines.push('### Orphan UUIDs (side-folder present, no JSONL)');
    lines.push('');
    if (pj.orphanUuids.sessionEnv.length) lines.push(`- **session-env** (${pj.orphanUuids.sessionEnv.length}): ${pj.orphanUuids.sessionEnv.map(u => `\`${u.slice(0, 8)}\``).join(', ')}`);
    if (pj.orphanUuids.tasks.length) lines.push(`- **tasks** (${pj.orphanUuids.tasks.length}): ${pj.orphanUuids.tasks.map(u => `\`${u.slice(0, 8)}\``).join(', ')}`);
    if (pj.orphanUuids.fileHistory.length) lines.push(`- **file-history** (${pj.orphanUuids.fileHistory.length}): ${pj.orphanUuids.fileHistory.map(u => `\`${u.slice(0, 8)}\``).join(', ')}`);
    lines.push('');
  }

  // Plans
  const pl = s.plans;
  lines.push('## Plans');
  lines.push('');
  const planSum = pl.summary;
  const totalBoxStr = planSum.totalCheckboxes
    ? `${planSum.totalCheckboxesDone}/${planSum.totalCheckboxes} checkboxes (${Math.round(planSum.totalCheckboxesDone / planSum.totalCheckboxes * 100)}%)`
    : 'no checkboxes';
  lines.push(`**Summary**: ${planSum.total} plans · ${planSum.active} active · ${planSum.stale} stale · ${planSum.dormant} dormant · ${planSum.complete} complete · ${totalBoxStr}`);
  lines.push('');
  lines.push('| Plan | Title | Progress | Age | Status | Explicit |');
  lines.push('|---|---|---|---|---|---|');
  for (const p of pl.plans) {
    const progress = p.checkboxes.total
      ? `${p.checkboxes.done}/${p.checkboxes.total} (${p.checkboxes.pct}%)`
      : '—';
    const ageStr = p.ageDays != null ? `${p.ageDays}d` : '—';
    const explicit = p.explicitStatus ? p.explicitStatus.slice(0, 40) : '—';
    const title = p.title ? p.title.replace(/\|/g, '\\|').slice(0, 50) : '—';
    lines.push(`| \`${p.name}\` | ${title} | ${progress} | ${ageStr} | ${p.lifecycleStatus || '—'} | ${explicit} |`);
  }
  lines.push('');

  // Runtime
  const rt = s.runtime;
  lines.push('## Runtime');
  lines.push('');
  lines.push('| Area | Count | Size | Notes |');
  lines.push('|---|---|---|---|');
  lines.push(`| history.jsonl | ${c.historyJsonl.missing ? 'missing' : `${c.historyJsonl.lines} lines`} | ${c.historyJsonl.missing ? '—' : humanSize(c.historyJsonl.size)} | |`);
  lines.push(`| backups | ${rt.backups.count} | ${humanSize(rt.backups.totalBytes)} | newest ${rt.backups.newest?.ageHours ?? '?'}h ago · oldest ${rt.backups.oldest?.ageDays ?? '?'}d${rt.backups.warnLarge ? ' · **LARGE**' : ''} |`);
  lines.push(`| shell-snapshots | ${rt.shellSnapshots.count} | ${humanSize(rt.shellSnapshots.totalBytes)} | oldest ${rt.shellSnapshots.oldest?.ageDays ?? '?'}d${rt.shellSnapshots.warnLarge ? ' · **LARGE**' : ''} |`);
  lines.push(`| cache | ${rt.cache.files.length} | ${humanSize(rt.cache.totalBytes)} | ${rt.cache.files.map(f => `${f.name} (${f.ageDays}d)`).join(', ') || '—'} |`);
  lines.push(`| downloads | ${rt.downloads.count} | ${humanSize(rt.downloads.totalBytes)} | ${rt.downloads.warnLarge ? '**LARGE**' : '—'} |`);
  lines.push(`| ide locks | ${rt.ide.lockFiles.length} | — | ${rt.ide.active ? `active: ${rt.ide.lockFiles.join(', ')}` : 'inactive'} |`);
  lines.push(`| runtime sessions | ${rt.runtimeSessions.count} | — | ${rt.runtimeSessions.files.map(f => f.name).join(', ') || '—'} |`);
  lines.push('');

  // GSD
  const gsd = s.gsd;
  lines.push('## GSD');
  lines.push('');
  if (!gsd.installed) {
    lines.push('- **Not installed** (`get-shit-done/` directory absent).');
  } else {
    lines.push(`- **Version**: ${gsd.version || '—'}`);
    const cs = Object.entries(gsd.counts).filter(([, v]) => v != null).map(([k, v]) => `${k}: ${v}`);
    if (cs.length) lines.push(`- **Contents**: ${cs.join(', ')}`);
    if (gsd.manifest.present) {
      lines.push(`- **Manifest**: ${gsd.manifest.fileCount} tracked files, version ${gsd.manifest.manifestVersion || '—'}, snapshot ${gsd.manifest.manifestTimestamp || '—'}`);
      if (gsd.manifest.drift) {
        lines.push(`- **Drift**: ${gsd.manifest.drift} files in manifest not found on disk`);
        for (const m of gsd.manifest.missing.slice(0, 10)) lines.push(`  - \`${m}\``);
        if (gsd.manifest.missing.length > 10) lines.push(`  - … +${gsd.manifest.missing.length - 10} more`);
      } else {
        lines.push('- **Drift**: none — all manifest files present');
      }
    } else {
      lines.push('- **Manifest**: absent');
    }
  }
  lines.push('');

  // Health & Drift
  const health = s.health || { issues: [], counts: { total: 0, error: 0, warn: 0, info: 0 } };
  lines.push('## Health & Drift');
  lines.push('');
  lines.push(`**${health.counts.total} issues** — ${health.counts.error} errors, ${health.counts.warn} warnings, ${health.counts.info} info. Full report: [health.md](health.md)`);
  lines.push('');
  if (health.counts.total === 0) {
    lines.push('All systems clean.');
    lines.push('');
  } else {
    for (const sev of ['error', 'warn', 'info']) {
      const group = health.issues.filter(i => i.severity === sev);
      if (!group.length) continue;
      lines.push(`**${sev.toUpperCase()}** (${group.length}):`);
      for (const iss of group) lines.push(`- [${iss.area}] ${iss.message}`);
      lines.push('');
    }
  }

  // Trends
  const hist = s.history;
  lines.push('## Trends');
  lines.push('');
  if (!hist || (!hist.previous && !hist.sevenDayAgo && !hist.thirtyDayAgo)) {
    lines.push(`**Snapshot history**: ${hist?.records || 0} record${(hist?.records || 0) === 1 ? '' : 's'}${hist?.records ? ` (earliest ${hist.earliestDate})` : ''}. Deltas appear once there are scans from prior days.`);
    lines.push('');
  } else {
    lines.push(`**Snapshot history**: ${hist.records} records · earliest ${hist.earliestDate} · retained 90d`);
    lines.push('');
    const cols = ['now'];
    const colPaths = [];
    if (hist.previous) { cols.push(`Δ prev (${hist.previous.date})`); colPaths.push('previous'); }
    if (hist.sevenDayAgo) { cols.push(`Δ ~7d (${hist.sevenDayAgo.date})`); colPaths.push('sevenDayAgo'); }
    if (hist.thirtyDayAgo) { cols.push(`Δ ~30d (${hist.thirtyDayAgo.date})`); colPaths.push('thirtyDayAgo'); }
    lines.push('| Metric | ' + cols.join(' | ') + ' |');
    lines.push('|' + '---|'.repeat(cols.length + 1));

    const fmtDelta = (cur, prev, isBytes) => {
      if (prev == null) return '—';
      const d = cur - prev;
      if (d === 0) return '—';
      const sign = d > 0 ? '+' : '-';
      const abs = Math.abs(d);
      return `${sign}${isBytes ? humanSize(abs) : abs}`;
    };

    const rows = [
      { label: 'Total size', get: r => r.totalBytes, bytes: true },
      { label: 'Memories', get: r => r.counts.memories },
      { label: 'Patterns', get: r => r.counts.patterns },
      { label: 'Reflections', get: r => r.counts.reflections },
      { label: 'Brain sessions', get: r => r.counts.sessions },
      { label: 'Agents', get: r => r.counts.agents },
      { label: 'Commands', get: r => r.counts.commands },
      { label: 'Skills', get: r => r.counts.skills },
      { label: 'Hooks wired', get: r => r.counts.hooksWired },
      { label: 'Projects', get: r => r.projects.projects },
      { label: 'Conversation sessions', get: r => r.projects.sessions },
      { label: 'JSONL records', get: r => r.projects.records },
      { label: 'JSONL bytes', get: r => r.projects.jsonlBytes, bytes: true },
      { label: 'Plans done/total', get: r => r.plans.done, total: r => r.plans.totalCheckboxes },
      { label: 'Health errors', get: r => r.health.error },
      { label: 'Health warnings', get: r => r.health.warn },
    ];

    for (const row of rows) {
      const curVal = row.get(hist.current);
      const curStr = row.total ? `${curVal}/${row.total(hist.current)}` : row.bytes ? humanSize(curVal) : String(curVal);
      const cells = [curStr];
      for (const p of colPaths) {
        const prior = hist[p];
        cells.push(prior ? fmtDelta(curVal, row.get(prior), row.bytes) : '—');
      }
      lines.push('| ' + row.label + ' | ' + cells.join(' | ') + ' |');
    }
    lines.push('');
  }

  // Workspaces
  if (Array.isArray(s.workspaces) && s.workspaces.length) {
    lines.push('## Workspaces');
    lines.push('');
    lines.push('| Workspace | Status | Summary | Next | Insight |');
    lines.push('|---|---|---|---|---|');
    for (const w of s.workspaces) {
      const esc = (t) => (t ? String(t).replace(/\|/g, '\\|').slice(0, 80) : '—');
      lines.push(`| \`${w.name}\` | ${w.status || '—'} | ${esc(w.summary)} | ${esc(w.next && w.next.text)} | ${esc(w.insight && w.insight.text)} |`);
    }
    lines.push('');
  }

  // Folder Atlas
  lines.push('## Folder Atlas');
  lines.push('');
  lines.push('| Folder | Entries | Files | Size | Newest |');
  lines.push('|---|---|---|---|---|');
  for (const f of s.folderAtlas) {
    if (!f.present) {
      lines.push(`| \`${f.name}/\` | — | — | — | **MISSING** |`);
      continue;
    }
    const newest = f.newestMtime ? f.newestMtime.slice(0, 10) : '—';
    lines.push(`| \`${f.name}/\` | ${f.entries} | ${f.files} | ${humanSize(f.bytes)} | ${newest} |`);
  }
  lines.push('');

  return lines.join('\n') + '\n';
}

// Generate/refresh insights (model or heuristic per provider) for workspaces whose cache is empty or stale.
async function enrichWorkspaceInsights(snapshot, provider) {
  if (!Array.isArray(snapshot.workspaces)) return;
  for (const ws of snapshot.workspaces) {
    if (ws.insight && ws.insight.status === 'ok' && ws.insight.inputHash === ws.inputHash) continue;
    const { insight, next } = await generateInsight(ws, { provider });
    ws.insight = insight;
    ws.next = next;
  }
}

async function main(report) {
  const argv = new Set(process.argv.slice(2));
  const cfg = loadConfig();
  const provider = await getProvider('scan-vault');
  if (report) report.provider = provider.name;
  const snapshot = scan();
  snapshot.provider = { name: provider.name, reason: provider.reason };
  await enrichWorkspaceInsights(snapshot, provider);

  try {
    const scannerCfg = (() => { try { return JSON.parse(fs.readFileSync(path.join(VAULT, 'brain', '_index', 'scanner-config.json'), 'utf8')); } catch { return {}; } })();
    snapshot.fileMaps = await collectFileMaps({ budget: scannerCfg.fileMapBudgetPerScan ?? cfg.scan.fileMapBudget, provider, report });
  } catch (e) {
    console.error('[scan-vault] fileMap collector failed:', e.message);
    snapshot.fileMaps = null;
  }

  try {
    const { buildBrainMd } = require('./build-brain-md.js');
    await withReport('build-brain-md', async (r) => { await buildBrainMd({ report: r }); });
  } catch (e) {
    console.error('[scan-vault] build-brain-md failed (loud in ledger):', e.message);
  }

  try {
    const { buildRecallIndex, saveIndex, writeWakeRecall } = require('./sdk/lib/recall.js');
    const recallIdx = buildRecallIndex();
    saveIndex(recallIdx);
    const wake = writeWakeRecall(recallIdx);
    if (report) {
      report.wrote.push('brain/_index/recall-index.json');
      if (wake) report.wrote.push('brain/_index/recall-wake.md');
    }
  } catch (e) {
    console.error('[scan-vault] recall-index failed:', e.message);
  }

  try {
    const { refreshEmbedIndex } = require('./embed-vault.js');
    await withReport('embed-vault', async (r) => {
      r.provider = provider.name;
      if (!provider.capabilities.embed) { r.disable('no-embed'); return; }
      const scannerCfg = (() => { try { return JSON.parse(fs.readFileSync(path.join(VAULT, 'brain', '_index', 'scanner-config.json'), 'utf8')); } catch { return {}; } })();
      const er = await refreshEmbedIndex({ budget: scannerCfg.embedBudgetPerScan ?? cfg.scan.embedBudget, provider });
      r.counts.embedded = er.embedded; r.counts.pending = er.pending; r.counts.failed = er.failed;
      r.wrote.push('brain/_index/embed-index.json');
      if (report) report.wrote.push(`brain/_index/embed-index.json (embedded ${er.embedded}, pending ${er.pending}, failed ${er.failed})`);
    });
  } catch (e) {
    console.error('[scan-vault] embed-index failed (loud in ledger):', e.message);
  }

  if (argv.has('--json')) {
    process.stdout.write(JSON.stringify(snapshot, null, 2));
    return;
  }

  const jsonPath = path.join(VAULT, 'brain/_index/snapshot.json');
  const mdPath = path.join(VAULT, 'brain/_index/snapshot.md');
  const healthPath = path.join(VAULT, 'brain/_index/health.md');
  const lockPath = path.join(VAULT, 'brain/_index/.snapshot.lock');
  // Atomic write: .tmp + rename so readers (the dashboard) never see a half-written file.
  const writeAtomic = (p, content) => {
    const tmp = p + '.tmp';
    fs.writeFileSync(tmp, content);
    fs.renameSync(tmp, p);
  };
  await withLock(lockPath, async () => {
    writeAtomic(jsonPath, JSON.stringify(snapshot, null, 2));
  });
  writeAtomic(mdPath, renderMarkdown(snapshot));
  writeAtomic(healthPath, renderHealthMarkdown(snapshot, snapshot.health));

  if (report) {
    report.wrote.push('brain/_index/snapshot.json', 'brain/_index/snapshot.md', 'brain/_index/health.md', `brain/_index/snapshots/${snapshot.scannedAt.slice(0, 10)}.json`);
  }

  writeDailyRecord(snapshot);
  const pruned = prune();
  try {
    const { pruneAgentRuns } = require('./lib/telemetry-retention.js');
    const tr = pruneAgentRuns({ runsDir: path.join(VAULT, 'brain', '_index', 'agent-runs'), retentionDays: cfg.telemetry.retentionDays });
    if (report) { report.counts.telemetryPrunedDirs = tr.removedDirs; report.counts.telemetryPrunedRows = tr.droppedRows; }
  } catch (e) {
    console.error('[scan-vault] telemetry retention failed:', e.message);
  }

  if (!argv.has('--quiet')) {
    const cap = snapshot.capabilities;
    const h = snapshot.health.counts;
    const totalBytes = snapshot.folderAtlas.reduce((a, f) => a + (f.bytes || 0), 0);
    process.stdout.write([
      `scanned ${snapshot.folderAtlas.length} folders in ${snapshot.elapsedMs}ms`,
      `agents:${cap.agents.count} cmds:${cap.commands.count} skills:${cap.skills.count} hooks:${cap.hooks.count}`,
      `health: ${h.error}E ${h.warn}W ${h.info}I`,
      `total:${humanSize(totalBytes)}`,
      `history:${snapshot.history.records}${pruned ? ` (pruned ${pruned})` : ''}`,
    ].join(' · ') + '\n');
  }
}

if (require.main === module) {
  // Hook mode (SessionEnd `scan-vault --quiet`): detach so session exit is never blocked.
  if (require('./lib/detach.js').respawnDetached()) process.exit(0);
  withReport('scan-vault', async (report) => {
    await main(report);
  }).catch((e) => { console.error('[scan-vault]', e.message); process.exit(1); });
}
module.exports = { scan, renderMarkdown };
