'use strict';
/**
 * codex-host.js — wires the Codex CLI as a session host (design D3/D4): hooks in <codex home>/hooks.json,
 * the agenticos MCP server through `codex mcp add`, and skills generated under ~/.agents/skills/ from the
 * vendored plugin/commands and plugin/skills. Everything written is idempotent and identifiable, so
 * `aos uninstall` removes exactly what `aos init` wrote and never a user's own hooks or skills.
 *
 *   hooks    every command is `env AOS_HOST=codex AOS_CONFIG='<config>' sh '<launcher>' <name>`; that prefix
 *            is the ownership marker (no extra keys, so Codex's hooks.json schema is untouched). Foreign
 *            entries and unknown top-level keys survive a merge and a removal. SessionEnd entries carry the
 *            3 s cap Codex enforces; every one of those handlers detaches its real work.
 *   mcp      `codex mcp add agenticos --env AOS_CONFIG=<config> --env AOS_HOST=codex -- sh <launcher> mcp-server`,
 *            skipped when `codex mcp get agenticos --json` already names that launcher with that env.
 *   skills   <skillsDir>/<name>/SKILL.md carries GENERATED_MARKER right under its frontmatter; only
 *            directories with that marker are ever removed or overwritten.
 *
 * That is the `direct` install. Where the Codex CLI installs plugins, `aos init` installs the `agenticos` plugin
 * instead (design 2026-09-23-codex-plugin): codex-plugin/ in the repo, generated from plugin/ by
 * tools/build-codex-plugin.js with the same HOOKS table and skill transforms (target 'plugin'), and the direct
 * wiring above is removed so the two never run side by side.
 *
 * Zero dependencies. Test seams: every entry point takes { run, env, io } overrides; AOS_CODEX_BIN names
 * the binary and AOS_NO_CODEX=1 hides it.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

/** Event → [command name, timeout seconds]. Mirrors plugin/hooks/hooks.json plus inject-conventions (D5). */
const HOOKS = [
  ['SessionStart', [['telemetry-hook', 10], ['update-notice', 10], ['persona-watchdog', 10], ['reconcile-sessions', 10], ['inject-conventions', 10]]],
  ['UserPromptSubmit', [['inject-context', 10]]],
  ['PostToolUse', [['telemetry-hook', 10]]],
  ['Stop', [['update-session', 10], ['heartbeat-writer', 10], ['reconcile-sessions', 10]]],
  ['SessionEnd', [['telemetry-hook', 3], ['auto-cost', 3], ['heartbeat-writer', 3], ['auto-wrap', 3], ['scan-vault --quiet', 3]]],
];
const OURS_RE = /^env AOS_HOST=codex /;
const GENERATED_MARKER = '<!-- generated by `aos init --host codex` from the AgenticOS Workbench plugin; edits are lost on `aos upgrade` -->';
// The Codex plugin (design 2026-09-23-codex-plugin): codex-plugin/ in the repo, listed by .agents/plugins/marketplace.json.
const PLUGIN_NAME = 'agenticos';
const MARKETPLACE = 'agenticos-workbench';
const PLUGIN_ID = `${PLUGIN_NAME}@${MARKETPLACE}`;
const PLUGIN_ROOT_REF = '<plugin root>';
const PLUGIN_MARKER = '<!-- generated by tools/build-codex-plugin.js from plugin/; edit the source there, not this file -->';
const DEFAULT_CANDIDATES = ['/opt/homebrew/bin/codex', '/usr/local/bin/codex', path.join(os.homedir(), '.local', 'bin', 'codex')];

// ── small helpers ─────────────────────────────────────────────────────────────
function shq(s) { return `'${String(s).replace(/'/g, `'\\''`)}'`; }
function exists(p) { return fs.existsSync(p); }
function isExecutable(p) { try { fs.accessSync(p, fs.constants.X_OK); return fs.statSync(p).isFile(); } catch { return false; } }
function readJson(p, fallback = null) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; } }
function safeParse(s) { try { return JSON.parse(s); } catch { return null; } }
function defaultRun(cmd, args, { capture = true, allowFail = true, env } = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', env: { ...process.env, ...(env || {}) }, stdio: capture ? ['ignore', 'pipe', 'pipe'] : 'inherit' });
  if (r.error) return { status: 127, stdout: '', stderr: String(r.error.message) };
  if (r.status !== 0 && !allowFail) throw new Error(`${cmd} ${args.join(' ')} exited ${r.status}`);
  return { status: r.status, stdout: r.stdout || '', stderr: r.stderr || '' };
}

// ── locations ─────────────────────────────────────────────────────────────────
function codexHome(cfg, env = process.env) {
  const fromCfg = cfg && cfg.hosts && cfg.hosts.codex && cfg.hosts.codex.home;
  return path.resolve(fromCfg || env.CODEX_HOME || path.join(os.homedir(), '.codex'));
}
function hooksFile(cfg, env) { return path.join(codexHome(cfg, env), 'hooks.json'); }
/** Codex scans ~/.agents/skills (canonical). HOME-based, so sandboxed tests never touch the real one. */
function skillsDir() { return path.join(os.homedir(), '.agents', 'skills'); }

/** AOS_CODEX_BIN (test knob) → recorded hosts.codex.bin while executable → PATH → the usual locations → null. */
function codexBin(cfg, { env = process.env, which } = {}) {
  if (env.AOS_NO_CODEX === '1') return null;
  if (env.AOS_CODEX_BIN) return env.AOS_CODEX_BIN;
  const recorded = cfg && cfg.hosts && cfg.hosts.codex && cfg.hosts.codex.bin;
  if (recorded && isExecutable(recorded)) return recorded;
  const lookup = which || ((name) => {
    const r = spawnSync('sh', ['-c', `command -v ${name}`], { encoding: 'utf8' });
    const p = (r.stdout || '').trim();
    return r.status === 0 && p ? p : null;
  });
  const found = lookup('codex');
  if (found) return found;
  return DEFAULT_CANDIDATES.find(isExecutable) || null;
}

/** `codex login status`: true iff it reports a login. */
function codexLoggedIn(bin, run = defaultRun) {
  if (!bin) return false;
  const r = run(bin, ['login', 'status'], { capture: true, allowFail: true });
  const out = `${r.stdout}\n${r.stderr}`;
  return r.status === 0 && /logged in/i.test(out) && !/not logged in/i.test(out);
}

/** Best effort: is Codex's built-in memories feature on? (`[memories]` table or `features.memories = true`.) */
function memoriesEnabled(cfg, env) {
  let toml = '';
  try { toml = fs.readFileSync(path.join(codexHome(cfg, env), 'config.toml'), 'utf8'); } catch { return false; }
  let section = '';
  for (const line of toml.split('\n')) {
    const head = line.match(/^\s*\[([^\]]+)\]/);
    if (head) { section = head[1].trim(); if (section === 'memories') return true; continue; }
    if (section === 'features' && /^\s*memories\s*=\s*true\b/.test(line)) return true;
  }
  return false;
}

// ── hooks.json ────────────────────────────────────────────────────────────────
function hookCommand({ launcher, config }, name) {
  return `env AOS_HOST=codex AOS_CONFIG=${shq(config)} sh ${shq(launcher)} ${name}`;
}
function isOurs(command) { return OURS_RE.test(String(command || '')); }
function isOurGroup(g) { return !!(g && Array.isArray(g.hooks) && g.hooks.length && g.hooks.every((h) => isOurs(h && h.command))); }

/** existing hooks.json document (or null) → the same document with our five entries present exactly once. */
function mergeHooks(existing, ctx) {
  const doc = existing && typeof existing === 'object' && !Array.isArray(existing) ? { ...existing } : {};
  const hooks = { ...(doc.hooks && typeof doc.hooks === 'object' ? doc.hooks : {}) };
  for (const [event, cmds] of HOOKS) {
    const foreign = (Array.isArray(hooks[event]) ? hooks[event] : []).filter((g) => !isOurGroup(g));
    const group = { hooks: cmds.map(([name, timeout]) => ({ type: 'command', command: hookCommand(ctx, name), timeout })) };
    hooks[event] = [...foreign, group];
  }
  doc.hooks = hooks;
  return doc;
}

/** Remove our entries. Returns { doc, removed }: doc is null when nothing else is left in the file. */
function stripHooks(existing) {
  if (!existing || typeof existing !== 'object' || Array.isArray(existing)) return { doc: null, removed: 0 };
  const doc = { ...existing };
  const hooks = {};
  let removed = 0;
  for (const [event, groups] of Object.entries(existing.hooks || {})) {
    const keep = (Array.isArray(groups) ? groups : []).filter((g) => { const ours = isOurGroup(g); if (ours) removed++; return !ours; });
    if (keep.length) hooks[event] = keep;
  }
  if (Object.keys(hooks).length) doc.hooks = hooks; else delete doc.hooks;
  return { doc: Object.keys(doc).length ? doc : null, removed };
}

/** How many of our events a hooks.json document registers (doctor). */
function countOurEvents(doc) {
  const hooks = doc && doc.hooks && typeof doc.hooks === 'object' ? doc.hooks : {};
  return HOOKS.filter(([event]) => (Array.isArray(hooks[event]) ? hooks[event] : []).some(isOurGroup)).length;
}

// ── MCP ───────────────────────────────────────────────────────────────────────
/** The `codex mcp add` argv. AOS_HOST=codex tells the MCP server which host spawned it (codex-parity D2); without it a
 *  wrap_session from a Codex session would resolve the Claude transcript directory on a two-host machine. */
function mcpAddArgs({ config, launcher }) {
  return ['mcp', 'add', 'agenticos', '--env', `AOS_CONFIG=${config}`, '--env', 'AOS_HOST=codex', '--', 'sh', launcher, 'mcp-server'];
}
/** 'ok' | 'stale' (names the launcher but its env lacks AOS_HOST=codex — a 0.5.0 registration) | 'missing' | 'no-binary' */
function mcpState({ bin, run = defaultRun, launcher }) {
  if (!bin) return 'no-binary';
  const r = run(bin, ['mcp', 'get', 'agenticos', '--json'], { capture: true, allowFail: true });
  if (r.status !== 0) return 'missing';
  const j = safeParse(r.stdout);
  const t = j && j.transport && typeof j.transport === 'object' ? j.transport : {};
  const args = Array.isArray(t.args) ? t.args : [];
  if (!(args.includes(launcher) && args.includes('mcp-server'))) return 'missing';
  const env = t.env && typeof t.env === 'object' ? t.env : {};
  return env.AOS_HOST === 'codex' ? 'ok' : 'stale';
}
function mcpRegistered(o) { return mcpState(o) === 'ok'; }
/** 'present' | 'added' | 'failed'. A stale registration (another launcher path, or one without AOS_HOST) is replaced. */
function registerMcp({ bin, run = defaultRun, launcher, config, io }) {
  if (mcpRegistered({ bin, run, launcher })) return 'present';
  run(bin, ['mcp', 'remove', 'agenticos'], { capture: true, allowFail: true });
  const addArgs = mcpAddArgs({ config, launcher });
  const r = run(bin, addArgs, { capture: true, allowFail: true });
  if (r.status !== 0) {
    if (io) io.warn(`codex mcp add failed (${(r.stderr || r.stdout).trim() || 'exit ' + r.status}); run: codex ${addArgs.join(' ')}`);
    return 'failed';
  }
  return 'added';
}

// ── skills ────────────────────────────────────────────────────────────────────
function parseFrontmatter(text) {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(text);
  if (!m) return { fm: {}, raw: '', body: text };
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = /^([A-Za-z-]+):\s*(.*)$/.exec(line);
    if (kv) fm[kv[1]] = kv[2];
  }
  return { fm, raw: m[1], body: text.slice(m[0].length) };
}

/**
 * A skill is generated for one of two targets. `direct` (the default) is a user skill under ~/.agents/skills that names
 * the vault's own launcher and config by absolute path. `plugin` is a skill inside codex-plugin/ (design
 * 2026-09-23-codex-plugin D3): a published plugin cannot know a user's paths, so it names `<plugin root>` (defined in
 * the host note) and keeps the config expression the launcher itself resolves; Codex lists it as `agenticos:<name>`.
 */
function isPlugin(ctx) { return ctx.target === 'plugin'; }
function invocation(ctx, name) { return isPlugin(ctx) ? `$${PLUGIN_NAME}:${name}` : `$${name}`; }
function markerFor(ctx) { return isPlugin(ctx) ? PLUGIN_MARKER : GENERATED_MARKER; }

/**
 * Wording that names the session the skill runs in, and invocations of this plugin's own commands (`/name` or
 * `/agenticos:name`) → the Codex forms. Applied to bodies and to frontmatter descriptions. Only "a/the/this/your Claude
 * Code session" is the current session; a qualified phrase ("an interactive Claude Code session") names Claude Code on
 * purpose and stays.
 */
function rewriteWording(text, ctx) {
  const { names } = ctx;
  let s = text.replace(/\b(a|the|this|your|each|every) Claude Code session/gi, (m, det) => `${det} Codex session`);
  if (names && names.length) {
    const alt = names.map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
    s = s.replace(new RegExp(`(^|[\\s(\`"'])/(?:${PLUGIN_NAME}:)?(${alt})(?![\\w/-])`, 'g'), (m, pre, n) => `${pre}${invocation(ctx, n)}`);
  }
  return s;
}

/** The Claude Code idioms a command or skill body uses → their Codex equivalents. */
function rewriteBody(body, ctx) {
  const { launcher, config, skillsDir: sdir, name } = ctx;
  const aos = isPlugin(ctx) ? `${PLUGIN_ROOT_REF}/bin/aos` : launcher;
  const skills = isPlugin(ctx) ? `${PLUGIN_ROOT_REF}/skills` : sdir;
  let s = body;
  s = s.replace(/sh "\$\{CLAUDE_PLUGIN_ROOT\}\/bin\/aos"/g, () => `sh "${aos}"`);
  s = s.replace(/\$\{CLAUDE_PLUGIN_ROOT\}\/skills\//g, () => `${skills}/`);
  s = s.replace(/\$\{CLAUDE_PLUGIN_ROOT\}\/bin\/aos/g, () => aos);
  if (!isPlugin(ctx)) s = s.replace(/\$\{CLAUDE_CONFIG_DIR:-(?:~|\$HOME)\/\.claude\}\/agenticos\.json/g, () => config);
  s = s.replace(/mcp__plugin_agenticos_agenticos__/g, 'mcp__agenticos__');
  s = s.replace(/\$ARGUMENTS/g, () => `the text the user wrote after \`${invocation(ctx, name)}\``);
  // Claude Code tools Codex has no counterpart for, in the phrasings the sources use: a file tool is just "read the
  // file"; a structured question becomes a question the host note explains how to ask.
  s = s.replace(/ with the (?:Read|Edit|Write|Glob|Grep) tool\b/g, '');
  s = s.replace(/\bAskUserQuestion(?: call)?\b/g, 'question');
  // The runner is told which host it runs in (spec 2026-09-23-cross-review D5): nothing in a Codex shell says so.
  s = s.replace(/--host claude\b/g, '--host codex');
  return rewriteWording(s, ctx);
}

function hostNote(ctx) {
  const ask = ctx.asks ? ' A question to the user is one message with its options numbered (where it says multiSelect, the user may pick several); wait for the reply before acting on it.' : '';
  if (isPlugin(ctx)) {
    return `> Host: Codex CLI, through the \`${PLUGIN_NAME}\` plugin. Invoke as \`${invocation(ctx, ctx.name)}\`. \`${PLUGIN_ROOT_REF}\` is the plugin's folder, two levels above the folder that holds this SKILL.md; the \`aos\` launcher is \`${PLUGIN_ROOT_REF}/bin/aos\`. The tools of the \`agenticos\` MCP server are named \`mcp__agenticos__<tool>\`.${ask}\n\n`;
  }
  return `> Host: Codex CLI. Invoke as \`${invocation(ctx, ctx.name)}\`. The \`aos\` launcher is \`${ctx.launcher}\`; the tools of the \`agenticos\` MCP server are named \`mcp__agenticos__<tool>\`.${ask}\n\n`;
}

const ASKS = /\bAskUserQuestion\b/;

/** plugin/commands/<name>.md → a Codex SKILL.md. */
function commandToSkill(name, text, ctx) {
  const { fm, body } = parseFrontmatter(text);
  const c = { ...ctx, name, asks: ASKS.test(body) };
  const description = rewriteWording(fm.description || `AgenticOS ${name}`, c);
  return `---\nname: ${name}\ndescription: ${description}\n---\n${markerFor(c)}\n\n${hostNote(c)}${rewriteBody(body, c).replace(/^\n+/, '')}`;
}

/** plugin/skills/<name>/SKILL.md → the same skill with Codex wording, the marker and the host note. */
function skillToCodex(name, text, ctx) {
  const { fm, raw, body } = parseFrontmatter(text);
  const c = { ...ctx, name: fm.name || name, asks: ASKS.test(body) };
  const head = rewriteWording(raw, c);
  return `---\n${head}\n---\n${markerFor(c)}\n\n${hostNote(c)}${rewriteBody(body, c).replace(/^\n+/, '')}`;
}

function isGenerated(skillMd, marker = GENERATED_MARKER) { try { return fs.readFileSync(skillMd, 'utf8').includes(marker); } catch { return false; } }

function copyDir(src, dest) {
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name);
    const d = path.join(dest, e.name);
    if (e.isDirectory()) { fs.mkdirSync(d, { recursive: true }); copyDir(s, d); }
    else if (e.isFile()) { fs.mkdirSync(path.dirname(d), { recursive: true }); fs.copyFileSync(s, d); }
  }
}

/**
 * Generate every command and skill of `pluginDir` into `dir`. A target that exists without our marker is
 * the user's and is left alone (reported in `skipped`). Returns { written, skipped }.
 */
function generateSkills({ pluginDir, dir, launcher, config, io, target = 'direct' }) {
  const cmdDir = path.join(pluginDir, 'commands');
  const skDir = path.join(pluginDir, 'skills');
  const commands = exists(cmdDir) ? fs.readdirSync(cmdDir).filter((f) => f.endsWith('.md')).map((f) => f.slice(0, -3)).sort() : [];
  const skills = exists(skDir) ? fs.readdirSync(skDir, { withFileTypes: true }).filter((e) => e.isDirectory() && exists(path.join(skDir, e.name, 'SKILL.md'))).map((e) => e.name).sort() : [];
  const names = [...new Set([...commands, ...skills])];
  const ctx = { launcher, config, skillsDir: dir, names, target };
  const written = [];
  const skipped = [];
  const place = (name, content, extraFrom) => {
    const target = path.join(dir, name);
    const md = path.join(target, 'SKILL.md');
    if (exists(md) && !isGenerated(md, markerFor(ctx))) {
      skipped.push(name);
      if (io) io.warn(`${md} exists and was not generated by aos; leaving it alone`);
      return;
    }
    fs.mkdirSync(target, { recursive: true });
    fs.writeFileSync(md, content);
    if (extraFrom) {
      for (const e of fs.readdirSync(extraFrom, { withFileTypes: true })) {
        if (e.name === 'SKILL.md') continue;
        const s = path.join(extraFrom, e.name);
        const d = path.join(target, e.name);
        if (e.isDirectory()) { fs.mkdirSync(d, { recursive: true }); copyDir(s, d); }
        else if (e.isFile()) fs.copyFileSync(s, d);
      }
    }
    written.push(name);
  };
  for (const name of commands) {
    if (skills.includes(name)) continue; // the skill of the same name (wrap) is the richer source; generated below
    place(name, commandToSkill(name, fs.readFileSync(path.join(cmdDir, `${name}.md`), 'utf8'), ctx));
  }
  for (const name of skills) {
    const src = path.join(skDir, name);
    let content = skillToCodex(name, fs.readFileSync(path.join(src, 'SKILL.md'), 'utf8'), ctx);
    if (commands.includes(name)) {
      // The command carried the step list the skill refers to ("continue the /wrap command's remaining steps"): append it.
      const cmd = fs.readFileSync(path.join(cmdDir, `${name}.md`), 'utf8');
      content += `\n\n## The \`${invocation(ctx, name)}\` procedure\n\n${rewriteBody(parseFrontmatter(cmd).body, { ...ctx, name }).replace(/^\n+/, '')}`;
    }
    place(name, content, src);
  }
  return { written, skipped };
}

/** Remove every generated skill under `dir`; returns the names removed. */
function removeSkills({ dir }) {
  const removed = [];
  let entries = [];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return removed; }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (!isGenerated(path.join(dir, e.name, 'SKILL.md'))) continue;
    fs.rmSync(path.join(dir, e.name), { recursive: true, force: true });
    removed.push(e.name);
  }
  return removed;
}
function countGenerated(dir) {
  try { return fs.readdirSync(dir, { withFileTypes: true }).filter((e) => e.isDirectory() && isGenerated(path.join(dir, e.name, 'SKILL.md'))).length; } catch { return 0; }
}

// ── entry points ──────────────────────────────────────────────────────────────
/**
 * Wire the host. `launcher` is <vault>/brain/scripts/bin/aos, `config` the agenticos.json path, `pluginDir` the
 * directory holding commands/ and skills/ (the vendored copy, else the checkout's plugin/).
 */
function installCodexHost({ cfg, launcher, config, pluginDir, bin, run = defaultRun, env = process.env, dir = skillsDir(), io = null }) {
  const file = hooksFile(cfg, env);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const before = readJson(file, null);
  const doc = mergeHooks(before, { launcher, config });
  const text = JSON.stringify(doc, null, 2) + '\n';
  const hooksChanged = !exists(file) || fs.readFileSync(file, 'utf8') !== text;
  if (hooksChanged) fs.writeFileSync(file, text);
  const mcp = bin ? registerMcp({ bin, run, launcher, config, io }) : 'no-binary';
  const skills = generateSkills({ pluginDir, dir, launcher, config, io });
  return { hooksFile: file, hooksChanged, mcp, skillsDir: dir, skills };
}

/** Reverse installCodexHost. Foreign hooks and skills stay; the file is deleted only when nothing else is in it. */
function removeCodexHost({ cfg, bin, run = defaultRun, env = process.env, dir = skillsDir(), io = null }) {
  const file = hooksFile(cfg, env);
  const { doc, removed } = stripHooks(readJson(file, null));
  let hooksFileState = 'absent';
  if (exists(file)) {
    if (doc) { fs.writeFileSync(file, JSON.stringify(doc, null, 2) + '\n'); hooksFileState = 'kept-foreign'; }
    else { fs.unlinkSync(file); hooksFileState = 'deleted'; }
  }
  let mcp = 'no-binary';
  if (bin) {
    const r = run(bin, ['mcp', 'remove', 'agenticos'], { capture: true, allowFail: true });
    mcp = r.status === 0 ? 'removed' : 'failed';
    if (r.status !== 0 && io) io.warn(`codex mcp remove agenticos failed (${(r.stderr || r.stdout).trim() || 'exit ' + r.status}); run it yourself`);
  }
  const skills = removeSkills({ dir });
  return { hooksFile: file, hooksFileState, hooksRemoved: removed, mcp, skills };
}

/** What doctor and status show. */
function codexHostStatus({ cfg, launcher, run = defaultRun, env = process.env, dir = skillsDir() }) {
  const bin = codexBin(cfg, { env });
  const file = hooksFile(cfg, env);
  return {
    bin,
    loggedIn: bin ? codexLoggedIn(bin, run) : false,
    hooksFile: file,
    hookEvents: countOurEvents(readJson(file, null)),
    hookEventsTotal: HOOKS.length,
    mcp: launcher ? mcpState({ bin, run, launcher }) : 'missing',
    skillsDir: dir,
    skills: countGenerated(dir),
    memories: memoriesEnabled(cfg, env),
  };
}

// ── the Codex plugin (design 2026-09-23-codex-plugin) ─────────────────────────
/** A hook command inside codex-plugin/hooks/hooks.json. Codex expands ${PLUGIN_ROOT} to the installed plugin folder
 *  and hashes the command before expansion, so trust survives version bumps; AOS_HOST=codex is authoritative (host.js). */
function pluginHookCommand(name) { return `env AOS_HOST=codex sh "\${PLUGIN_ROOT}/bin/aos" ${name}`; }
/** codex-plugin/.mcp.json. Codex does not expand ${PLUGIN_ROOT} in MCP args, so the launcher is relative to cwd ".",
 *  which Codex resolves to the installed plugin folder. A published plugin cannot name the user's config: the
 *  launcher's own default applies, and AOS_CONFIG / CLAUDE_CONFIG_DIR pass through when the user sets them. */
function pluginMcpServers() {
  return { mcpServers: { agenticos: { command: 'sh', args: ['./bin/aos', 'mcp-server'], cwd: '.', env: { AOS_HOST: 'codex' }, env_vars: ['AOS_CONFIG', 'CLAUDE_CONFIG_DIR'] } } };
}
/** Hook entries codex-plugin registers: one trust decision each in Codex. */
function pluginHookCount() { return HOOKS.reduce((n, [, cmds]) => n + cmds.length, 0); }

function pluginList(bin, run) {
  const r = run(bin, ['plugin', 'list', '--json'], { capture: true, allowFail: true });
  const j = r.status === 0 ? safeParse(r.stdout) : null;
  return j && Array.isArray(j.installed) ? j : null;
}
/** 'plugin' when this Codex CLI installs plugins (`codex plugin list --json` answers with a list), else 'direct'. */
function codexInstallMode(bin, run = defaultRun) { return bin && pluginList(bin, run) ? 'plugin' : 'direct'; }
/** Whether agenticos@agenticos-workbench is installed in this Codex. */
function codexPluginInstalled(bin, run = defaultRun) {
  const list = bin ? pluginList(bin, run) : null;
  return !!(list && list.installed.some((p) => p && p.pluginId === PLUGIN_ID && p.installed !== false));
}

/**
 * Add the marketplace and install (or reinstall) the plugin. `source` is a local checkout or owner/repo. An existing
 * marketplace from another source is kept unless `switchSource` (an explicit --from-local); a kept or re-added git
 * marketplace is refreshed first. Returns { state: 'installed' | 'failed', version, installedPath, source }.
 */
function installCodexPlugin({ bin, source, switchSource = false, run = defaultRun, io = null }) {
  const warn = (m) => { if (io) io.warn(m); };
  const mkt = ['plugin', 'marketplace'];
  let add = run(bin, [...mkt, 'add', source, '--json'], { capture: true, allowFail: true });
  let refresh = add.status === 0 && !!(safeParse(add.stdout) || {}).alreadyAdded;
  if (add.status !== 0 && /different source/i.test(add.stderr + add.stdout)) {
    if (switchSource) {
      run(bin, [...mkt, 'remove', MARKETPLACE], { capture: true, allowFail: true });
      add = run(bin, [...mkt, 'add', source, '--json'], { capture: true, allowFail: true });
    } else {
      refresh = true;
      add = { status: 0, stdout: '', stderr: '' };
    }
  }
  if (add.status !== 0) {
    warn(`codex plugin marketplace add failed (${(add.stderr || add.stdout).trim() || 'exit ' + add.status}); run: codex plugin marketplace add ${source}`);
    return { state: 'failed', source };
  }
  // A git marketplace needs a fetch to see a new version; a local one is read in place (upgrade exits 1 there, ignored).
  if (refresh) run(bin, [...mkt, 'upgrade', MARKETPLACE], { capture: true, allowFail: true });
  const inst = run(bin, ['plugin', 'add', PLUGIN_ID, '--json'], { capture: true, allowFail: true });
  const j = inst.status === 0 ? safeParse(inst.stdout) : null;
  if (!j) {
    warn(`codex plugin add failed (${(inst.stderr || inst.stdout).trim() || 'exit ' + inst.status}); run: codex plugin add ${PLUGIN_ID}`);
    return { state: 'failed', source };
  }
  return { state: 'installed', version: j.version || null, installedPath: j.installedPath || null, source };
}

/**
 * The agenticos-workbench marketplace's folder in this Codex (`codex plugin marketplace list --json` → `root`): the
 * checkout it was added from, or Codex's snapshot of the repository for a git source. `aos upgrade` vendors from it
 * when no Claude Code marketplace exists (a Codex-only machine); `refresh` fetches a git snapshot first so it vendors
 * the current release. null when there is no binary, no such marketplace, or no root.
 */
function codexMarketplaceRoot({ bin, run = defaultRun, refresh = false } = {}) {
  if (!bin) return null;
  const find = () => {
    const r = run(bin, ['plugin', 'marketplace', 'list', '--json'], { capture: true, allowFail: true });
    const j = r.status === 0 ? safeParse(r.stdout) : null;
    return (j && Array.isArray(j.marketplaces) && j.marketplaces.find((m) => m && m.name === MARKETPLACE)) || null;
  };
  let m = find();
  if (m && refresh && m.marketplaceSource && m.marketplaceSource.sourceType === 'git') {
    run(bin, ['plugin', 'marketplace', 'upgrade', MARKETPLACE], { capture: true, allowFail: true });
    m = find() || m;
  }
  return m && typeof m.root === 'string' && m.root ? path.resolve(m.root) : null;
}

/** Uninstall the plugin and drop the marketplace. Returns { plugin, marketplace } as 'removed' | 'failed' | 'no-binary'. */
function removeCodexPlugin({ bin, run = defaultRun, io = null }) {
  if (!bin) return { plugin: 'no-binary', marketplace: 'no-binary' };
  const p = run(bin, ['plugin', 'remove', PLUGIN_ID], { capture: true, allowFail: true });
  if (p.status !== 0 && io) io.warn(`codex plugin remove ${PLUGIN_ID} failed (${(p.stderr || p.stdout).trim() || 'exit ' + p.status}); run it yourself`);
  const m = run(bin, ['plugin', 'marketplace', 'remove', MARKETPLACE], { capture: true, allowFail: true });
  const gone = m.status === 0 || /not configured/i.test(m.stderr + m.stdout);
  return { plugin: p.status === 0 ? 'removed' : 'failed', marketplace: gone ? 'removed' : 'failed' };
}

/**
 * Remove what `aos init --host codex` used to write directly (design D5: never both). Our hook entries, the generated
 * skills (marker only), and the `agenticos` MCP registration in the user's config — `codex mcp remove` never touches a
 * plugin's server. Returns { hooks, mcp, skills }: entries stripped, whether a registration went, skills deleted.
 */
function removeDirectWiring({ cfg, bin, run = defaultRun, env = process.env, dir = skillsDir() }) {
  const file = hooksFile(cfg, env);
  let hooks = 0;
  const before = readJson(file, null);
  if (countOurEvents(before)) {
    const { doc, removed } = stripHooks(before);
    hooks = removed;
    if (doc) fs.writeFileSync(file, JSON.stringify(doc, null, 2) + '\n'); else fs.unlinkSync(file);
  }
  let mcp = false;
  if (bin) {
    const r = run(bin, ['mcp', 'remove', 'agenticos'], { capture: true, allowFail: true });
    mcp = r.status === 0 && !/no mcp server/i.test(r.stdout + r.stderr);
  }
  return { hooks, mcp, skills: removeSkills({ dir }).length };
}

/** Our hook entries Codex has trusted: `[hooks.state."agenticos@agenticos-workbench:hooks/hooks.json:…"]` tables with a trusted_hash. */
function trustedPluginHooks(cfg, env) {
  let toml = '';
  try { toml = fs.readFileSync(path.join(codexHome(cfg, env), 'config.toml'), 'utf8'); } catch { return 0; }
  const prefix = `[hooks.state."${PLUGIN_ID}:hooks/hooks.json:`;
  const trusted = new Set();
  let key = null;
  for (const line of toml.split('\n')) {
    const t = line.trim();
    if (t.startsWith('[')) { key = t.startsWith(prefix) ? t : null; continue; }
    if (key && /^trusted_hash\s*=\s*"sha256:[0-9a-f]+"/.test(t)) trusted.add(key);
  }
  return trusted.size;
}

/** What doctor and status show in plugin mode. mcp: 'ok' (the plugin's server, ./bin/aos with AOS_HOST=codex) | 'missing'. */
function codexPluginStatus({ cfg, launcher, run = defaultRun, env = process.env, dir = skillsDir() }) {
  const bin = codexBin(cfg, { env });
  const list = bin ? pluginList(bin, run) : null;
  const entry = list && list.installed.find((p) => p && p.pluginId === PLUGIN_ID && p.installed !== false);
  let mcp = 'missing';
  if (bin) {
    const r = run(bin, ['mcp', 'list', '--json'], { capture: true, allowFail: true });
    const arr = r.status === 0 ? safeParse(r.stdout) : null;
    const s = Array.isArray(arr) ? arr.find((x) => x && x.name === 'agenticos') : null;
    const t = s && s.transport && typeof s.transport === 'object' ? s.transport : {};
    const args = Array.isArray(t.args) ? t.args : [];
    if (args.includes('./bin/aos') && args.includes('mcp-server') && t.env && t.env.AOS_HOST === 'codex') mcp = 'ok';
  }
  return {
    bin,
    loggedIn: bin ? codexLoggedIn(bin, run) : false,
    installed: !!entry,
    version: entry ? entry.version || null : null,
    trusted: trustedPluginHooks(cfg, env),
    hooksTotal: pluginHookCount(),
    mcp,
    direct: {
      hookEvents: countOurEvents(readJson(hooksFile(cfg, env), null)),
      mcp: launcher && bin ? ['ok', 'stale'].includes(mcpState({ bin, run, launcher })) : false,
      skills: countGenerated(dir),
    },
    memories: memoriesEnabled(cfg, env),
  };
}

module.exports = {
  HOOKS, GENERATED_MARKER, PLUGIN_NAME, MARKETPLACE, PLUGIN_ID, PLUGIN_ROOT_REF, PLUGIN_MARKER,
  pluginHookCommand, pluginMcpServers, pluginHookCount, codexInstallMode, codexPluginInstalled, installCodexPlugin, removeCodexPlugin,
  codexMarketplaceRoot,
  removeDirectWiring, trustedPluginHooks, codexPluginStatus,
  codexHome, hooksFile, skillsDir, codexBin, codexLoggedIn, memoriesEnabled,
  hookCommand, isOurs, mergeHooks, stripHooks, countOurEvents,
  mcpAddArgs, mcpState, mcpRegistered, registerMcp,
  parseFrontmatter, rewriteBody, commandToSkill, skillToCodex, generateSkills, removeSkills, countGenerated,
  installCodexHost, removeCodexHost, codexHostStatus,
};
