'use strict';
/**
 * codex-host.js — wires the Codex CLI as a session host (design D3/D4): hooks in <codex home>/hooks.json,
 * the agenticos MCP server through `codex mcp add`, and skills generated under ~/.agents/skills/ from the
 * vendored plugin/commands and plugin/skills. Everything written is idempotent and identifiable, so
 * `aos uninstall` removes exactly what `aos init` wrote and never a user's own hooks or skills.
 *
 *   hooks    every command is `env AOS_HOST=codex AOS_CONFIG='<config>' sh '<launcher>' <name>`; that prefix
 *            is the ownership marker (no extra keys, so Codex's hooks.json schema is untouched). Foreign
 *            entries and unknown top-level keys survive a merge and a removal. SessionEnd entries carry the
 *            3 s cap Codex enforces; every one of those handlers detaches its real work.
 *   mcp      `codex mcp add agenticos --env AOS_CONFIG=<config> --env AOS_HOST=codex -- sh <launcher> mcp-server`,
 *            skipped when `codex mcp get agenticos --json` already names that launcher with that env.
 *   skills   <skillsDir>/<name>/SKILL.md carries GENERATED_MARKER right under its frontmatter; only
 *            directories with that marker are ever removed or overwritten.
 *
 * Zero dependencies. Test seams: every entry point takes { run, env, io } overrides; AOS_CODEX_BIN names
 * the binary and AOS_NO_CODEX=1 hides it.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

/** Event → [command name, timeout seconds]. Mirrors plugin/hooks/hooks.json plus inject-conventions (D5). */
const HOOKS = [
  ['SessionStart', [['telemetry-hook', 10], ['update-notice', 10], ['persona-watchdog', 10], ['inject-conventions', 10]]],
  ['UserPromptSubmit', [['inject-context', 10]]],
  ['PostToolUse', [['telemetry-hook', 10]]],
  ['Stop', [['update-session', 10], ['heartbeat-writer', 10]]],
  ['SessionEnd', [['telemetry-hook', 3], ['auto-cost', 3], ['heartbeat-writer', 3], ['auto-wrap', 3], ['scan-vault --quiet', 3]]],
];
const OURS_RE = /^env AOS_HOST=codex /;
const GENERATED_MARKER = '<!-- generated by `aos init --host codex` from the AgenticOS Workbench plugin; edits are lost on `aos upgrade` -->';
const DEFAULT_CANDIDATES = ['/opt/homebrew/bin/codex', '/usr/local/bin/codex', path.join(os.homedir(), '.local', 'bin', 'codex')];

// ── small helpers ─────────────────────────────────────────────────────────────
function shq(s) { return `'${String(s).replace(/'/g, `'\\''`)}'`; }
function exists(p) { return fs.existsSync(p); }
function isExecutable(p) { try { fs.accessSync(p, fs.constants.X_OK); return fs.statSync(p).isFile(); } catch { return false; } }
function readJson(p, fallback = null) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; } }
function safeParse(s) { try { return JSON.parse(s); } catch { return null; } }
function defaultRun(cmd, args, { capture = true, allowFail = true, env } = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', env: { ...process.env, ...(env || {}) }, stdio: capture ? ['ignore', 'pipe', 'pipe'] : 'inherit' });
  if (r.error) return { status: 127, stdout: '', stderr: String(r.error.message) };
  if (r.status !== 0 && !allowFail) throw new Error(`${cmd} ${args.join(' ')} exited ${r.status}`);
  return { status: r.status, stdout: r.stdout || '', stderr: r.stderr || '' };
}

// ── locations ─────────────────────────────────────────────────────────────────
function codexHome(cfg, env = process.env) {
  const fromCfg = cfg && cfg.hosts && cfg.hosts.codex && cfg.hosts.codex.home;
  return path.resolve(fromCfg || env.CODEX_HOME || path.join(os.homedir(), '.codex'));
}
function hooksFile(cfg, env) { return path.join(codexHome(cfg, env), 'hooks.json'); }
/** Codex scans ~/.agents/skills (canonical). HOME-based, so sandboxed tests never touch the real one. */
function skillsDir() { return path.join(os.homedir(), '.agents', 'skills'); }

/** AOS_CODEX_BIN (test knob) → recorded hosts.codex.bin while executable → PATH → the usual locations → null. */
function codexBin(cfg, { env = process.env, which } = {}) {
  if (env.AOS_NO_CODEX === '1') return null;
  if (env.AOS_CODEX_BIN) return env.AOS_CODEX_BIN;
  const recorded = cfg && cfg.hosts && cfg.hosts.codex && cfg.hosts.codex.bin;
  if (recorded && isExecutable(recorded)) return recorded;
  const lookup = which || ((name) => {
    const r = spawnSync('sh', ['-c', `command -v ${name}`], { encoding: 'utf8' });
    const p = (r.stdout || '').trim();
    return r.status === 0 && p ? p : null;
  });
  const found = lookup('codex');
  if (found) return found;
  return DEFAULT_CANDIDATES.find(isExecutable) || null;
}

/** `codex login status`: true iff it reports a login. */
function codexLoggedIn(bin, run = defaultRun) {
  if (!bin) return false;
  const r = run(bin, ['login', 'status'], { capture: true, allowFail: true });
  const out = `${r.stdout}\n${r.stderr}`;
  return r.status === 0 && /logged in/i.test(out) && !/not logged in/i.test(out);
}

/** Best effort: is Codex's built-in memories feature on? (`[memories]` table or `features.memories = true`.) */
function memoriesEnabled(cfg, env) {
  let toml = '';
  try { toml = fs.readFileSync(path.join(codexHome(cfg, env), 'config.toml'), 'utf8'); } catch { return false; }
  let section = '';
  for (const line of toml.split('\n')) {
    const head = line.match(/^\s*\[([^\]]+)\]/);
    if (head) { section = head[1].trim(); if (section === 'memories') return true; continue; }
    if (section === 'features' && /^\s*memories\s*=\s*true\b/.test(line)) return true;
  }
  return false;
}

// ── hooks.json ────────────────────────────────────────────────────────────────
function hookCommand({ launcher, config }, name) {
  return `env AOS_HOST=codex AOS_CONFIG=${shq(config)} sh ${shq(launcher)} ${name}`;
}
function isOurs(command) { return OURS_RE.test(String(command || '')); }
function isOurGroup(g) { return !!(g && Array.isArray(g.hooks) && g.hooks.length && g.hooks.every((h) => isOurs(h && h.command))); }

/** existing hooks.json document (or null) → the same document with our five entries present exactly once. */
function mergeHooks(existing, ctx) {
  const doc = existing && typeof existing === 'object' && !Array.isArray(existing) ? { ...existing } : {};
  const hooks = { ...(doc.hooks && typeof doc.hooks === 'object' ? doc.hooks : {}) };
  for (const [event, cmds] of HOOKS) {
    const foreign = (Array.isArray(hooks[event]) ? hooks[event] : []).filter((g) => !isOurGroup(g));
    const group = { hooks: cmds.map(([name, timeout]) => ({ type: 'command', command: hookCommand(ctx, name), timeout })) };
    hooks[event] = [...foreign, group];
  }
  doc.hooks = hooks;
  return doc;
}

/** Remove our entries. Returns { doc, removed }: doc is null when nothing else is left in the file. */
function stripHooks(existing) {
  if (!existing || typeof existing !== 'object' || Array.isArray(existing)) return { doc: null, removed: 0 };
  const doc = { ...existing };
  const hooks = {};
  let removed = 0;
  for (const [event, groups] of Object.entries(existing.hooks || {})) {
    const keep = (Array.isArray(groups) ? groups : []).filter((g) => { const ours = isOurGroup(g); if (ours) removed++; return !ours; });
    if (keep.length) hooks[event] = keep;
  }
  if (Object.keys(hooks).length) doc.hooks = hooks; else delete doc.hooks;
  return { doc: Object.keys(doc).length ? doc : null, removed };
}

/** How many of our events a hooks.json document registers (doctor). */
function countOurEvents(doc) {
  const hooks = doc && doc.hooks && typeof doc.hooks === 'object' ? doc.hooks : {};
  return HOOKS.filter(([event]) => (Array.isArray(hooks[event]) ? hooks[event] : []).some(isOurGroup)).length;
}

// ── MCP ───────────────────────────────────────────────────────────────────────
/** The `codex mcp add` argv. AOS_HOST=codex tells the MCP server which host spawned it (codex-parity D2); without it a
 *  wrap_session from a Codex session would resolve the Claude transcript directory on a two-host machine. */
function mcpAddArgs({ config, launcher }) {
  return ['mcp', 'add', 'agenticos', '--env', `AOS_CONFIG=${config}`, '--env', 'AOS_HOST=codex', '--', 'sh', launcher, 'mcp-server'];
}
/** 'ok' | 'stale' (names the launcher but its env lacks AOS_HOST=codex — a 0.5.0 registration) | 'missing' | 'no-binary' */
function mcpState({ bin, run = defaultRun, launcher }) {
  if (!bin) return 'no-binary';
  const r = run(bin, ['mcp', 'get', 'agenticos', '--json'], { capture: true, allowFail: true });
  if (r.status !== 0) return 'missing';
  const j = safeParse(r.stdout);
  const t = j && j.transport && typeof j.transport === 'object' ? j.transport : {};
  const args = Array.isArray(t.args) ? t.args : [];
  if (!(args.includes(launcher) && args.includes('mcp-server'))) return 'missing';
  const env = t.env && typeof t.env === 'object' ? t.env : {};
  return env.AOS_HOST === 'codex' ? 'ok' : 'stale';
}
function mcpRegistered(o) { return mcpState(o) === 'ok'; }
/** 'present' | 'added' | 'failed'. A stale registration (another launcher path, or one without AOS_HOST) is replaced. */
function registerMcp({ bin, run = defaultRun, launcher, config, io }) {
  if (mcpRegistered({ bin, run, launcher })) return 'present';
  run(bin, ['mcp', 'remove', 'agenticos'], { capture: true, allowFail: true });
  const addArgs = mcpAddArgs({ config, launcher });
  const r = run(bin, addArgs, { capture: true, allowFail: true });
  if (r.status !== 0) {
    if (io) io.warn(`codex mcp add failed (${(r.stderr || r.stdout).trim() || 'exit ' + r.status}); run: codex ${addArgs.join(' ')}`);
    return 'failed';
  }
  return 'added';
}

// ── skills ────────────────────────────────────────────────────────────────────
function parseFrontmatter(text) {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(text);
  if (!m) return { fm: {}, raw: '', body: text };
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = /^([A-Za-z-]+):\s*(.*)$/.exec(line);
    if (kv) fm[kv[1]] = kv[2];
  }
  return { fm, raw: m[1], body: text.slice(m[0].length) };
}

/** The Claude Code idioms a command or skill body uses → their Codex equivalents. */
function rewriteBody(body, { launcher, config, skillsDir: sdir, name, names }) {
  let s = body;
  s = s.replace(/sh "\$\{CLAUDE_PLUGIN_ROOT\}\/bin\/aos"/g, `sh "${launcher}"`);
  s = s.replace(/\$\{CLAUDE_PLUGIN_ROOT\}\/skills\//g, `${sdir}/`);
  s = s.replace(/\$\{CLAUDE_PLUGIN_ROOT\}\/bin\/aos/g, launcher);
  s = s.replace(/\$\{CLAUDE_CONFIG_DIR:-(?:~|\$HOME)\/\.claude\}\/agenticos\.json/g, config);
  s = s.replace(/mcp__plugin_agenticos_agenticos__/g, 'mcp__agenticos__');
  s = s.replace(/\$ARGUMENTS/g, `the text the user wrote after \`$${name}\``);
  s = s.replace(/Claude Code session/g, 'Codex session');
  if (names && names.length) {
    const alt = names.map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
    s = s.replace(new RegExp(`(^|[\\s(\`])/(${alt})(?![\\w/-])`, 'g'), (m, pre, n) => `${pre}$${n}`);
  }
  return s;
}

function hostNote({ launcher, name }) {
  return `> Host: Codex CLI. Invoke as \`$${name}\`. The \`aos\` launcher is \`${launcher}\`; the tools of the \`agenticos\` MCP server are named \`mcp__agenticos__<tool>\`.\n\n`;
}

/** plugin/commands/<name>.md → a Codex SKILL.md. */
function commandToSkill(name, text, ctx) {
  const { fm, body } = parseFrontmatter(text);
  const description = fm.description || `AgenticOS ${name}`;
  const c = { ...ctx, name };
  return `---\nname: ${name}\ndescription: ${description}\n---\n${GENERATED_MARKER}\n\n${hostNote(c)}${rewriteBody(body, c).replace(/^\n+/, '')}`;
}

/** plugin/skills/<name>/SKILL.md → the same skill with Codex wording, the marker and the host note. */
function skillToCodex(name, text, ctx) {
  const { fm, raw, body } = parseFrontmatter(text);
  const c = { ...ctx, name: fm.name || name };
  const head = raw.replace(/Claude Code session/g, 'Codex session');
  return `---\n${head}\n---\n${GENERATED_MARKER}\n\n${hostNote(c)}${rewriteBody(body, c).replace(/^\n+/, '')}`;
}

function isGenerated(skillMd) { try { return fs.readFileSync(skillMd, 'utf8').includes(GENERATED_MARKER); } catch { return false; } }

function copyDir(src, dest) {
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name);
    const d = path.join(dest, e.name);
    if (e.isDirectory()) { fs.mkdirSync(d, { recursive: true }); copyDir(s, d); }
    else if (e.isFile()) { fs.mkdirSync(path.dirname(d), { recursive: true }); fs.copyFileSync(s, d); }
  }
}

/**
 * Generate every command and skill of `pluginDir` into `dir`. A target that exists without our marker is
 * the user's and is left alone (reported in `skipped`). Returns { written, skipped }.
 */
function generateSkills({ pluginDir, dir, launcher, config, io }) {
  const cmdDir = path.join(pluginDir, 'commands');
  const skDir = path.join(pluginDir, 'skills');
  const commands = exists(cmdDir) ? fs.readdirSync(cmdDir).filter((f) => f.endsWith('.md')).map((f) => f.slice(0, -3)).sort() : [];
  const skills = exists(skDir) ? fs.readdirSync(skDir, { withFileTypes: true }).filter((e) => e.isDirectory() && exists(path.join(skDir, e.name, 'SKILL.md'))).map((e) => e.name).sort() : [];
  const names = [...new Set([...commands, ...skills])];
  const ctx = { launcher, config, skillsDir: dir, names };
  const written = [];
  const skipped = [];
  const place = (name, content, extraFrom) => {
    const target = path.join(dir, name);
    const md = path.join(target, 'SKILL.md');
    if (exists(md) && !isGenerated(md)) {
      skipped.push(name);
      if (io) io.warn(`${md} exists and was not generated by aos; leaving it alone`);
      return;
    }
    fs.mkdirSync(target, { recursive: true });
    fs.writeFileSync(md, content);
    if (extraFrom) {
      for (const e of fs.readdirSync(extraFrom, { withFileTypes: true })) {
        if (e.name === 'SKILL.md') continue;
        const s = path.join(extraFrom, e.name);
        const d = path.join(target, e.name);
        if (e.isDirectory()) { fs.mkdirSync(d, { recursive: true }); copyDir(s, d); }
        else if (e.isFile()) fs.copyFileSync(s, d);
      }
    }
    written.push(name);
  };
  for (const name of commands) {
    if (skills.includes(name)) continue; // the skill of the same name (wrap) is the richer source; generated below
    place(name, commandToSkill(name, fs.readFileSync(path.join(cmdDir, `${name}.md`), 'utf8'), ctx));
  }
  for (const name of skills) {
    const src = path.join(skDir, name);
    let content = skillToCodex(name, fs.readFileSync(path.join(src, 'SKILL.md'), 'utf8'), ctx);
    if (commands.includes(name)) {
      // The command carried the step list the skill refers to ("continue the /wrap command's remaining steps"): append it.
      const cmd = fs.readFileSync(path.join(cmdDir, `${name}.md`), 'utf8');
      content += `\n\n## The \`$${name}\` procedure\n\n${rewriteBody(parseFrontmatter(cmd).body, { ...ctx, name }).replace(/^\n+/, '')}`;
    }
    place(name, content, src);
  }
  return { written, skipped };
}

/** Remove every generated skill under `dir`; returns the names removed. */
function removeSkills({ dir }) {
  const removed = [];
  let entries = [];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return removed; }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (!isGenerated(path.join(dir, e.name, 'SKILL.md'))) continue;
    fs.rmSync(path.join(dir, e.name), { recursive: true, force: true });
    removed.push(e.name);
  }
  return removed;
}
function countGenerated(dir) {
  try { return fs.readdirSync(dir, { withFileTypes: true }).filter((e) => e.isDirectory() && isGenerated(path.join(dir, e.name, 'SKILL.md'))).length; } catch { return 0; }
}

// ── entry points ──────────────────────────────────────────────────────────────
/**
 * Wire the host. `launcher` is <vault>/brain/scripts/bin/aos, `config` the agenticos.json path, `pluginDir` the
 * directory holding commands/ and skills/ (the vendored copy, else the checkout's plugin/).
 */
function installCodexHost({ cfg, launcher, config, pluginDir, bin, run = defaultRun, env = process.env, dir = skillsDir(), io = null }) {
  const file = hooksFile(cfg, env);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const before = readJson(file, null);
  const doc = mergeHooks(before, { launcher, config });
  const text = JSON.stringify(doc, null, 2) + '\n';
  const hooksChanged = !exists(file) || fs.readFileSync(file, 'utf8') !== text;
  if (hooksChanged) fs.writeFileSync(file, text);
  const mcp = bin ? registerMcp({ bin, run, launcher, config, io }) : 'no-binary';
  const skills = generateSkills({ pluginDir, dir, launcher, config, io });
  return { hooksFile: file, hooksChanged, mcp, skillsDir: dir, skills };
}

/** Reverse installCodexHost. Foreign hooks and skills stay; the file is deleted only when nothing else is in it. */
function removeCodexHost({ cfg, bin, run = defaultRun, env = process.env, dir = skillsDir(), io = null }) {
  const file = hooksFile(cfg, env);
  const { doc, removed } = stripHooks(readJson(file, null));
  let hooksFileState = 'absent';
  if (exists(file)) {
    if (doc) { fs.writeFileSync(file, JSON.stringify(doc, null, 2) + '\n'); hooksFileState = 'kept-foreign'; }
    else { fs.unlinkSync(file); hooksFileState = 'deleted'; }
  }
  let mcp = 'no-binary';
  if (bin) {
    const r = run(bin, ['mcp', 'remove', 'agenticos'], { capture: true, allowFail: true });
    mcp = r.status === 0 ? 'removed' : 'failed';
    if (r.status !== 0 && io) io.warn(`codex mcp remove agenticos failed (${(r.stderr || r.stdout).trim() || 'exit ' + r.status}); run it yourself`);
  }
  const skills = removeSkills({ dir });
  return { hooksFile: file, hooksFileState, hooksRemoved: removed, mcp, skills };
}

/** What doctor and status show. */
function codexHostStatus({ cfg, launcher, run = defaultRun, env = process.env, dir = skillsDir() }) {
  const bin = codexBin(cfg, { env });
  const file = hooksFile(cfg, env);
  return {
    bin,
    loggedIn: bin ? codexLoggedIn(bin, run) : false,
    hooksFile: file,
    hookEvents: countOurEvents(readJson(file, null)),
    hookEventsTotal: HOOKS.length,
    mcp: launcher ? mcpState({ bin, run, launcher }) : 'missing',
    skillsDir: dir,
    skills: countGenerated(dir),
    memories: memoriesEnabled(cfg, env),
  };
}

module.exports = {
  HOOKS, GENERATED_MARKER, codexHome, hooksFile, skillsDir, codexBin, codexLoggedIn, memoriesEnabled,
  hookCommand, isOurs, mergeHooks, stripHooks, countOurEvents,
  mcpAddArgs, mcpState, mcpRegistered, registerMcp,
  parseFrontmatter, rewriteBody, commandToSkill, skillToCodex, generateSkills, removeSkills, countGenerated,
  installCodexHost, removeCodexHost, codexHostStatus,
};
