#!/usr/bin/env node
'use strict';
/**
 * scan-arsenal.js — inventories the skills, agents, and commands under a Claude Code
 * config dir (skills/<name>/SKILL.md, agents/*.md, commands/*.md) as JSON.
 * Used to bootstrap <vault>/persona/PLAYBOOK.md (build-playbook.js) and to detect
 * playbook drift during the weekly reflect duty.
 *
 *   node persona/scan-arsenal.js [--root <configDir>]     (default: PATHS.CLAUDE_CONFIG_DIR)
 *
 * Where Codex is a host it also lists Codex's own user skills (~/.agents/skills/<name>/SKILL.md), custom prompts
 * (<codex home>/prompts/*.md, as commands) and user agents (<codex home>/agents/*.toml), each with host: 'codex'; skills
 * our direct wiring generated (the `aos init --host codex` marker) are the Workbench's own and stay out, like the
 * plugin's own under Claude Code.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');

const EXCLUDE_FILES = new Set(['INDEX.md', 'README.md']);
// lib/skills.js marks every skill it mirrors from the other host with this sidecar (spec 2026-09-23-universal-skills D8):
// the playbook lists each skill once, under the host that owns it.
const MIRROR_SIDECAR = '.aos-mirror.json';
// lib/agents.js marks every agent it mirrors with an `# aos-mirror:` comment (spec 2026-09-23-universal-agents D8): the
// playbook lists each agent once too, under the host that owns it.
const AT = require('../lib/agent-translate.js');
const DESC_MAX = 200;

function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  const fm = {};
  if (!m) return fm;
  const lines = m[1].split('\n');
  for (let i = 0; i < lines.length; i++) {
    const kv = lines[i].match(/^(name|description):\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    let val = kv[2].trim();
    // YAML block scalars put the value on the following indented lines.
    if (/^[>|][-+]?$/.test(val)) {
      const buf = [];
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].trim() && !/^[ \t]/.test(lines[j])) break;
        buf.push(lines[j].trim());
      }
      val = buf.filter(Boolean).join(' ');
    }
    fm[key] = unquote(val);
  }
  return fm;
}

function unquote(s) {
  const t = (s || '').trim();
  return /^(".*"|'.*')$/s.test(t) ? t.slice(1, -1).trim() : t;
}

function firstHeading(text) {
  const body = text.replace(/^---\n[\s\S]*?\n---\n?/, '');
  const m = body.match(/^#\s+(.+)$/m);
  if (m) return m[1].trim();
  // No frontmatter description and no H1 (many commands) -> first prose line.
  for (const line of body.split('\n')) {
    if (line.trim()) return line.trim();
  }
  return '';
}

function clip(s) {
  return (s || '').slice(0, DESC_MAX);
}

/** Codex's skill and prompt folders when Codex is an enabled host (agenticos.json), else null. */
function codexSources() {
  try {
    const H = require('../lib/host.js');
    const cfg = require('../lib/paths.js').readUserConfig();
    if (!H.enabledHosts(cfg).includes('codex')) return null;
    const home = H.hostDirs('codex', { userConfig: cfg }).configDir;
    return { skillsDir: path.join(os.homedir(), '.agents', 'skills'), promptsDir: path.join(home, 'prompts'), agentsDir: path.join(home, 'agents') };
  } catch { return null; }
}

function scanCodex({ skillsDir, promptsDir, agentsDir }, out) {
  if (skillsDir && fs.existsSync(skillsDir)) {
    for (const dir of fs.readdirSync(skillsDir)) {
      const skillMd = path.join(skillsDir, dir, 'SKILL.md');
      if (!fs.existsSync(skillMd) || fs.existsSync(path.join(skillsDir, dir, MIRROR_SIDECAR))) continue;
      const text = fs.readFileSync(skillMd, 'utf8');
      if (text.includes('generated by `aos init --host codex`')) continue;
      const fm = parseFrontmatter(text);
      out.push({ type: 'skill', name: fm.name || dir, description: clip(fm.description || firstHeading(text)), path: skillMd, host: 'codex' });
    }
  }
  if (promptsDir && fs.existsSync(promptsDir)) {
    for (const f of fs.readdirSync(promptsDir)) {
      const full = path.join(promptsDir, f);
      if (!f.endsWith('.md') || EXCLUDE_FILES.has(f) || !fs.statSync(full).isFile()) continue;
      const text = fs.readFileSync(full, 'utf8');
      const fm = parseFrontmatter(text);
      out.push({ type: 'command', name: fm.name || f.slice(0, -3), description: clip(fm.description || firstHeading(text)), path: full, host: 'codex' });
    }
  }
  if (agentsDir && fs.existsSync(agentsDir)) {
    for (const f of fs.readdirSync(agentsDir)) {
      const full = path.join(agentsDir, f);
      if (!f.endsWith('.toml') || !fs.statSync(full).isFile()) continue;
      const text = fs.readFileSync(full, 'utf8');
      if (AT.readMarker(text, 'toml')) continue;
      const a = AT.readCodex(text);
      if (!a.ok) continue;
      out.push({ type: 'agent', name: a.name || f.slice(0, -5), description: clip(a.description), path: full, host: 'codex' });
    }
  }
}

function scanArsenal(root, { codex } = {}) {
  if (!root) throw new Error('scanArsenal(root): root (the Claude config dir) is required');
  const out = [];

  const skillsDir = path.join(root, 'skills');
  if (fs.existsSync(skillsDir)) {
    for (const dir of fs.readdirSync(skillsDir)) {
      const skillMd = path.join(skillsDir, dir, 'SKILL.md');
      if (!fs.existsSync(skillMd) || fs.existsSync(path.join(skillsDir, dir, MIRROR_SIDECAR))) continue;
      const text = fs.readFileSync(skillMd, 'utf8');
      const fm = parseFrontmatter(text);
      out.push({
        type: 'skill',
        name: fm.name || dir,
        description: clip(fm.description || firstHeading(text)),
        path: skillMd,
      });
    }
  }

  for (const [type, sub] of [['agent', 'agents'], ['command', 'commands']]) {
    const dir = path.join(root, sub);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith('.md') || EXCLUDE_FILES.has(f)) continue;
      const full = path.join(dir, f);
      if (!fs.statSync(full).isFile()) continue;
      const text = fs.readFileSync(full, 'utf8');
      if (type === 'agent' && AT.readMarker(text, 'md')) continue;
      const fm = parseFrontmatter(text);
      const base = f.replace(/\.md$/, '');
      out.push({
        type,
        name: fm.name || base,
        description: clip(fm.description || firstHeading(text)),
        path: full,
      });
    }
  }

  const cx = codex === undefined ? codexSources() : codex;
  if (cx) scanCodex(cx, out);

  out.sort((a, b) => a.type.localeCompare(b.type) || a.name.localeCompare(b.name));
  return out;
}

if (require.main === module) {
  const rootIdx = process.argv.indexOf('--root');
  const root = rootIdx !== -1 ? process.argv[rootIdx + 1] : require('../lib/paths.js').PATHS.CLAUDE_CONFIG_DIR;
  process.stdout.write(JSON.stringify(scanArsenal(root), null, 2) + '\n');
}

module.exports = { scanArsenal };
