'use strict';
/**
 * skills.js — every skill of both session hosts in one list, and the sync that makes each host's user skills universal
 * (spec 2026-09-23-universal-skills).
 *
 *   discover(roots)            what is on disk: each host's user skills (Claude Code also its claude.ai-synced ones),
 *                              our mirrors, the enabled plugins' skills and commands, Codex's built-ins
 *   plan(found, opts)          one row per skill with its status (D3) and the mirror writes/removals that make it so
 *   apply(actions)             performs them; every write re-checks ownership (the `.aos-mirror.json` sidecar) first
 *   sync({ vault, userCfg })   discover → plan → apply → brain/_index/skills.json (D7); the hook, the CLI and the HUD
 *                              all end up here
 *
 * A mirror is a folder in the other host's user scope: a translated SKILL.md (lib/skill-translate.js), a symlink per
 * other top-level entry of the source, and the sidecar { schema, id, from, source, sourceHash, writtenHash, at } (D1).
 * A folder without the sidecar is never written or removed; a mirror whose SKILL.md no longer hashes to writtenHash was
 * edited by hand and is left alone until `aos skills reset <name>` (D3). Plugin skills and built-ins are listed only
 * (D2). Every root is injectable, so tests never touch a real home.
 */
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const T = require('./skill-translate.js');
const H = require('./host.js');

const SCHEMA = 1;
const SIDECAR = '.aos-mirror.json';
const DIRECT_MARKER = 'generated by `aos init --host codex`';
const DISPLAY_MAX = 300;
const HOSTS = ['claude', 'codex'];

function sha(text) { return crypto.createHash('sha256').update(text).digest('hex'); }
function readText(p) { try { return fs.readFileSync(p, 'utf8'); } catch { return null; } }
function readJson(p) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } }
function isFile(p) { try { return fs.statSync(p).isFile(); } catch { return false; } }
function isDir(p) { try { return fs.statSync(p).isDirectory(); } catch { return false; } }
function listDirs(dir) {
  try { return fs.readdirSync(dir).filter((n) => !n.startsWith('.') && isDir(path.join(dir, n))).sort(); } catch { return []; }
}

// ── config and roots ─────────────────────────────────────────────────────────

/** skills config by loadConfig() precedence: the shipped defaults ← <vault>/brain/config.json ← agenticos.json. */
function skillsConfig({ vault, userCfg } = {}) {
  const defaults = readJson(path.join(__dirname, '..', 'config.default.json')) || {};
  const vaultCfg = (vault && readJson(path.join(vault, 'brain', 'config.json'))) || {};
  const layers = [defaults.skills, vaultCfg.skills, userCfg && userCfg.skills].map((x) => x || {});
  const s = Object.assign({ sync: true, exclude: [] }, ...layers);
  s.exclude = Array.isArray(s.exclude) ? s.exclude.map((n) => String(n).toLowerCase()) : [];
  return s;
}

/** The enabled session hosts; a config without `hosts` predates Codex and means Claude Code only. */
function hostsOf(userCfg) {
  const on = H.enabledHosts(userCfg);
  return on.length ? on : ['claude'];
}

/** Where each host keeps what we read and write. */
function roots({ userCfg = null, env = process.env, home = os.homedir() } = {}) {
  const claude = path.resolve((userCfg && userCfg.claudeConfigDir) || H.claudeConfigDir(env));
  const codex = H.codexHome(env, userCfg);
  return {
    claudeSkills: path.join(claude, 'skills'),
    claudePlugins: path.join(claude, 'plugins', 'installed_plugins.json'),
    claudeSettings: path.join(claude, 'settings.json'),
    codexSkills: path.join(home, '.agents', 'skills'),
    codexSystem: path.join(codex, 'skills', '.system'),
    codexConfig: path.join(codex, 'config.toml'),
    codexPluginCache: path.join(codex, 'plugins', 'cache'),
  };
}

// ── discovery ────────────────────────────────────────────────────────────────

/** One skill folder, or null when it holds no SKILL.md file. */
function readSkill(dir) {
  const md = path.join(dir, 'SKILL.md');
  if (!isFile(md)) return null;
  const text = readText(md);
  if (text === null) return null;
  const p = T.parse(text);
  const folder = path.basename(dir);
  return {
    dir, folder, md, text, hash: sha(text), has: p.has,
    name: p.fm.name || folder,
    description: T.clip(p.fm.description || T.firstProse(p.body), DISPLAY_MAX),
    sidecar: readJson(path.join(dir, SIDECAR)),
  };
}

function skillsIn(dir) { return listDirs(dir).map((n) => readSkill(path.join(dir, n))).filter(Boolean); }

/** Claude Code plugins that are installed and enabled: [{ plugin, root }]. */
function claudePlugins(r) {
  const installed = readJson(r.claudePlugins);
  const enabled = (readJson(r.claudeSettings) || {}).enabledPlugins;
  const out = [];
  for (const [key, entries] of Object.entries((installed && installed.plugins) || {})) {
    if (enabled && typeof enabled === 'object' && enabled[key] !== true) continue;
    const list = Array.isArray(entries) ? entries : [entries];
    const hit = list.find((e) => e && e.installPath && isDir(e.installPath));
    if (hit) out.push({ plugin: key.split('@')[0], root: hit.installPath });
  }
  return out;
}

/** `[plugins."name@market"]` sections of config.toml whose `enabled` is not false: [{ plugin, market }]. */
function codexEnabledPlugins(toml) {
  const out = [];
  let cur = null;
  for (const line of String(toml || '').split(/\r?\n/)) {
    const sec = line.match(/^\s*\[plugins\."([^"@]+)@([^"]+)"\]\s*$/);
    if (sec) { cur = { plugin: sec[1], market: sec[2], enabled: true }; out.push(cur); continue; }
    if (/^\s*\[/.test(line)) { cur = null; continue; }
    const kv = cur && line.match(/^\s*enabled\s*=\s*(true|false)\b/);
    if (kv) cur.enabled = kv[1] === 'true';
  }
  return out.filter((p) => p.enabled).map(({ plugin, market }) => ({ plugin, market }));
}

/** The newest cached version of a Codex plugin that has skills: cache/<market>[-*]/<plugin>/<version>/. */
function codexPluginRoot(cache, { plugin, market }) {
  let markets = [];
  try { markets = fs.readdirSync(cache).filter((m) => m === market || m.startsWith(`${market}-`)); } catch { return null; }
  markets.sort((a, b) => (a === market ? -1 : b === market ? 1 : a.localeCompare(b)));
  for (const m of markets) {
    const base = path.join(cache, m, plugin);
    const versions = listDirs(base).map((v) => path.join(base, v)).filter((v) => isDir(path.join(v, 'skills')));
    if (!versions.length) continue;
    versions.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
    return versions[0];
  }
  return null;
}

/** A plugin command file (Claude Code `commands/<name>.md`) as a listed entry. */
function readCommand(file) {
  const text = readText(file);
  if (text === null) return null;
  const p = T.parse(text);
  const name = path.basename(file, '.md');
  return { md: file, name, description: T.clip(p.fm.description || T.firstProse(p.body), DISPLAY_MAX) };
}

function discover(r) {
  const found = { claude: { user: [], synced: [], mirrors: [] }, codex: { user: [], mirrors: [] }, listed: [] };
  for (const s of skillsIn(r.claudeSkills)) {
    if (s.folder === 'synced') continue;
    (s.sidecar ? found.claude.mirrors : found.claude.user).push(s);
  }
  for (const id of listDirs(path.join(r.claudeSkills, 'synced'))) found.claude.synced.push(...skillsIn(path.join(r.claudeSkills, 'synced', id)));
  for (const s of skillsIn(r.codexSkills)) {
    if (s.sidecar) { found.codex.mirrors.push(s); continue; }
    // Our own direct wiring (`aos init --host codex` on an older CLI): the agenticos plugin's skills, listed as such.
    if (s.text.includes(DIRECT_MARKER)) { found.listed.push({ host: 'codex', scope: 'plugin', plugin: 'agenticos', name: s.name, description: s.description, path: s.md, invoke: `$${s.name}` }); continue; }
    found.codex.user.push(s);
  }
  for (const { plugin, root } of claudePlugins(r)) {
    for (const s of skillsIn(path.join(root, 'skills'))) found.listed.push({ host: 'claude', scope: 'plugin', plugin, name: s.name, description: s.description, path: s.md, invoke: `/${plugin}:${s.folder}` });
    let cmds = [];
    try { cmds = fs.readdirSync(path.join(root, 'commands')).filter((f) => f.endsWith('.md')).sort(); } catch { /* no commands */ }
    for (const f of cmds) {
      const c = readCommand(path.join(root, 'commands', f));
      if (c) found.listed.push({ host: 'claude', scope: 'plugin', plugin, name: c.name, description: c.description, path: c.md, invoke: `/${plugin}:${c.name}` });
    }
  }
  for (const p of codexEnabledPlugins(readText(r.codexConfig))) {
    const root = codexPluginRoot(r.codexPluginCache, p);
    if (!root) continue;
    for (const s of skillsIn(path.join(root, 'skills'))) found.listed.push({ host: 'codex', scope: 'plugin', plugin: p.plugin, name: s.name, description: s.description, path: s.md, invoke: `$${p.plugin}:${s.name}` });
  }
  for (const s of skillsIn(r.codexSystem)) found.listed.push({ host: 'codex', scope: 'builtin', plugin: null, name: s.name, description: s.description, path: s.md, invoke: `$${s.name}` });
  return found;
}

// ── plan ─────────────────────────────────────────────────────────────────────

function idOf(s) { return T.codexName(s.name) || T.codexName(s.folder) || s.folder.toLowerCase(); }

/** A mirror is current when its SKILL.md still hashes to what we wrote. */
function isEdited(m) { return !m.sidecar || m.sidecar.writtenHash !== m.hash; }

/** Folder name and translation for mirroring `src` (native on `from`) into the other host. */
function translate(src, from, names, r) {
  if (from === 'claude') {
    const name = T.codexName(src.name) || T.codexName(src.folder);
    const dir = path.join(r.codexSkills, name || src.folder);
    return { dir, res: T.toCodex(src.text, { name, dir, source: src.dir, names: names.toCodex }) };
  }
  const name = src.name;
  const dir = path.join(r.claudeSkills, name);
  return { dir, res: T.toClaude(src.text, { name, dir, source: src.dir, names: names.toClaude }) };
}

/**
 * Rows (D7) and actions. `on` is what each host will have once the actions ran: { path, via, invoke } or null.
 * opts: { roots, config: skillsConfig(), hosts: enabled hosts }.
 */
function plan(found, { roots: r, config, hosts }) {
  const bothHosts = HOSTS.every((h) => hosts.includes(h));
  const syncOn = config.sync !== false && bothHosts;
  const offReason = config.sync === false ? 'sharing is off (skills.sync is false)' : bothHosts ? null : 'sharing needs both hosts enabled';
  const exclude = new Set(config.exclude || []);

  // Native user skills per id: Claude Code's own folder wins over a claude.ai-synced copy of the same name.
  const ids = new Map();
  const slot = (id) => { if (!ids.has(id)) ids.set(id, { claude: null, codex: null, scope: null, mirror: { claude: null, codex: null } }); return ids.get(id); };
  for (const s of found.claude.user) { const e = slot(idOf(s)); if (!e.claude) { e.claude = s; e.scope = 'user'; } }
  for (const s of found.claude.synced) { const e = slot(idOf(s)); if (!e.claude) { e.claude = s; e.scope = 'synced'; } }
  for (const s of found.codex.user) { const e = slot(idOf(s)); if (!e.codex) e.codex = s; }
  for (const m of found.claude.mirrors) slot(m.sidecar.id || idOf(m)).mirror.claude = m;
  for (const m of found.codex.mirrors) slot(m.sidecar.id || idOf(m)).mirror.codex = m;

  // Cross-references the translator rewrites: a user skill both hosts will have, and a plugin skill both hosts list.
  const names = { toCodex: new Map(), toClaude: new Map() };
  const listedBoth = new Map();
  for (const l of found.listed) {
    const k = `${l.plugin || 'builtin'}:${l.name}`;
    const e = listedBoth.get(k) || {};
    e[l.host] = l.invoke.slice(1);
    listedBoth.set(k, e);
  }
  for (const [k, e] of listedBoth) {
    if (!e.claude || !e.codex) continue;
    names.toCodex.set(e.claude, e.codex);
    names.toCodex.set(k.split(':').slice(1).join(':'), e.codex);
    names.toClaude.set(e.codex, e.claude);
  }
  for (const [id, e] of ids) {
    if (!(e.claude && e.codex) && (exclude.has(id) || !(e.claude || e.codex))) continue;
    // Each side's name for the skill, native or mirrored: Claude Code runs a folder, Codex a frontmatter name.
    const claudeName = e.claude ? e.claude.folder : e.codex.name;
    const codexName = e.codex ? e.codex.name : T.codexName(e.claude.name) || T.codexName(e.claude.folder);
    names.toCodex.set(claudeName, codexName);
    names.toClaude.set(codexName, claudeName);
  }

  const rows = [];
  const actions = [];
  const removeIfClean = (m) => { if (m && !isEdited(m)) actions.push({ type: 'remove', id: idOf(m), dir: m.dir }); };
  const on = (s, via) => (s ? { path: s.md, via, invoke: null } : null);

  for (const [id, e] of [...ids].sort((a, b) => a[0].localeCompare(b[0]))) {
    const src = e.claude || e.codex;
    const row = {
      id,
      name: e.claude ? e.claude.folder : (src ? src.name : id),
      description: src ? src.description : '',
      origin: src ? { host: e.claude ? 'claude' : 'codex', scope: e.claude ? e.scope : 'user', plugin: null, path: src.md } : null,
      on: { claude: on(e.claude, 'native'), codex: on(e.codex, 'native') },
      status: 'universal',
      note: null,
    };

    if (!src) {
      // Only mirrors are left: their source is gone. A clean one goes with it; an edited one is the user's now.
      for (const h of HOSTS) {
        const m = e.mirror[h];
        if (!m) continue;
        if (isEdited(m)) {
          row.name = h === 'claude' ? m.folder : m.name;
          row.description = m.description;
          row.origin = { host: h, scope: 'mirror', plugin: null, path: m.md };
          row.on[h] = on(m, 'mirror');
          row.status = 'edited';
          row.note = `the source was removed and this copy was edited: delete ${m.dir} or keep it as your own`;
        } else if (syncOn) actions.push({ type: 'remove', id, dir: m.dir });
      }
      if (row.origin) rows.push(row);
      continue;
    }

    if (e.claude && e.codex) {
      row.status = e.claude.hash === e.codex.hash ? 'universal' : 'differs';
      if (row.status === 'differs') row.note = 'a different SKILL.md on each host; the sync leaves both alone';
      if (syncOn) { removeIfClean(e.mirror.claude); removeIfClean(e.mirror.codex); }
      rows.push(row);
      continue;
    }

    const from = e.claude ? 'claude' : 'codex';
    const to = from === 'claude' ? 'codex' : 'claude';
    const mirror = e.mirror[to];
    const { dir, res } = translate(src, from, names, r);

    if (exclude.has(id)) {
      row.status = 'excluded';
      row.note = `not shared (aos skills include ${id})`;
      if (syncOn) removeIfClean(mirror);
      if (mirror && isEdited(mirror)) row.on[to] = on(mirror, 'mirror');
    } else if (!res.ok) {
      row.status = 'invalid';
      row.note = res.reason;
      if (syncOn) removeIfClean(mirror);
    } else if (mirror && path.resolve(mirror.dir) !== path.resolve(dir)) {
      // The source was renamed: the old mirror goes (when clean) and a new one is written below.
      if (syncOn) removeIfClean(mirror);
      if (mirror && isEdited(mirror)) { row.status = 'edited'; row.note = `the copy at ${mirror.dir} was edited; aos skills reset ${id} replaces it`; row.on[to] = on(mirror, 'mirror'); }
      else if (!syncOn) { row.status = 'pending'; row.note = offReason; }
      else { actions.push(mirrorAction(id, from, src, dir, res)); row.on[to] = { path: path.join(dir, 'SKILL.md'), via: 'mirror', invoke: null }; }
    } else if (mirror && isEdited(mirror)) {
      row.status = 'edited';
      row.note = `the copy at ${mirror.dir} was edited; aos skills reset ${id} replaces it`;
      row.on[to] = on(mirror, 'mirror');
    } else if (!mirror && fs.existsSync(dir)) {
      row.status = 'differs';
      row.note = `${dir} exists and is not an AgenticOS mirror; the sync leaves it alone`;
    } else if (!syncOn) {
      row.status = mirror && mirror.text === res.content ? 'universal' : 'pending';
      if (row.status === 'pending') row.note = offReason;
      if (mirror) row.on[to] = on(mirror, 'mirror');
    } else {
      actions.push(mirrorAction(id, from, src, dir, res));
      row.on[to] = { path: path.join(dir, 'SKILL.md'), via: 'mirror', invoke: null };
    }
    rows.push(row);
  }

  // Invocations: Claude Code runs a user skill by its folder name, Codex by its frontmatter name.
  for (const row of rows) {
    const c = row.on.claude;
    const x = row.on.codex;
    if (c) c.invoke = `/${path.basename(path.dirname(c.path))}`;
    if (x) x.invoke = `$${x.via === 'native' ? (ids.get(row.id).codex || {}).name || row.id : T.codexName(path.basename(path.dirname(x.path))) || row.id}`;
  }

  // Plugin skills and built-ins: listed, merged across hosts when the same plugin ships the same skill on both.
  const merged = new Map();
  for (const l of found.listed) {
    const key = `${l.scope}:${l.plugin || ''}:${l.name}`;
    const row = merged.get(key) || {
      id: l.plugin ? `${l.plugin}:${l.name}` : l.name,
      name: l.name,
      description: l.description,
      origin: { host: l.host, scope: l.scope, plugin: l.plugin, path: l.path },
      on: { claude: null, codex: null },
      status: 'listed',
      note: l.scope === 'builtin' ? `built into ${l.host === 'codex' ? 'Codex' : 'Claude Code'}` : `from the ${l.plugin} plugin`,
    };
    if (!row.on[l.host]) row.on[l.host] = { path: l.path, via: l.scope, invoke: l.invoke };
    if (!row.description) row.description = l.description;
    merged.set(key, row);
  }
  const listed = [...merged.values()].sort((a, b) => (a.origin.plugin || '~').localeCompare(b.origin.plugin || '~') || a.name.localeCompare(b.name));

  return { rows: [...rows, ...listed], actions, sync: { on: syncOn, reason: offReason } };
}

function mirrorAction(id, from, src, dir, res) {
  return { type: 'mirror', id, from, source: src.dir, sourceHash: src.hash, dir, content: res.content };
}

// ── apply ────────────────────────────────────────────────────────────────────

function writeAtomic(file, text) {
  const tmp = `${file}.${process.pid}.tmp`;
  try { fs.writeFileSync(tmp, text); fs.renameSync(tmp, file); }
  catch (e) { try { fs.rmSync(tmp, { force: true }); } catch { /* already gone */ } throw e; }
}

function lstat(p) { try { return fs.lstatSync(p); } catch { return null; } }

/** The source's other top-level entries as symlinks in the mirror; stale links into the source go. Returns true on change. */
function syncLinks(source, dir) {
  let changed = false;
  let want = [];
  try { want = fs.readdirSync(source).filter((n) => n !== 'SKILL.md' && n !== SIDECAR && !n.startsWith('.')); } catch { /* source unreadable */ }
  const src = path.resolve(source);
  for (const n of want) {
    const link = path.join(dir, n);
    const target = path.join(src, n);
    const st = lstat(link);
    if (st && st.isSymbolicLink() && fs.readlinkSync(link) === target) continue;
    if (st && !st.isSymbolicLink()) continue; // a real file the user put there: theirs
    if (st) fs.unlinkSync(link);
    fs.symlinkSync(target, link);
    changed = true;
  }
  let have = [];
  try { have = fs.readdirSync(dir); } catch { /* new dir */ }
  for (const n of have) {
    const link = path.join(dir, n);
    const st = lstat(link);
    if (!st || !st.isSymbolicLink() || want.includes(n)) continue;
    if (inside(fs.readlinkSync(link), src)) { fs.unlinkSync(link); changed = true; }
  }
  return changed;
}

/** A mirror folder is ours to touch only while its sidecar exists and its SKILL.md still hashes to what we wrote. */
function stillOurs(dir) {
  const side = readJson(path.join(dir, SIDECAR));
  if (!side) return false;
  const text = readText(path.join(dir, 'SKILL.md'));
  return text !== null && sha(text) === side.writtenHash;
}

function applyMirror(a, now) {
  const md = path.join(a.dir, 'SKILL.md');
  const exists = fs.existsSync(a.dir);
  if (exists && !stillOurs(a.dir)) throw new Error(`${a.dir} changed since the plan; left alone`);
  fs.mkdirSync(a.dir, { recursive: true });
  let changed = false;
  if (readText(md) !== a.content) { writeAtomic(md, a.content); changed = true; }
  if (syncLinks(a.source, a.dir)) changed = true;
  const side = { schema: SCHEMA, id: a.id, from: a.from, source: path.resolve(a.source), sourceHash: a.sourceHash, writtenHash: sha(a.content) };
  const cur = readJson(path.join(a.dir, SIDECAR));
  const same = cur && Object.keys(side).every((k) => cur[k] === side[k]);
  if (!same) { writeAtomic(path.join(a.dir, SIDECAR), `${JSON.stringify({ ...side, at: now.toISOString() }, null, 2)}\n`); changed = true; }
  return changed;
}

function inside(p, dir) { return p === dir || p.startsWith(`${dir}${path.sep}`); }

/**
 * Removes only what a mirror is made of (SKILL.md, the sidecar, our symlinks into the source), then the folder when it
 * is empty. Without `force` it refuses an edited mirror; `aos skills reset` passes force to discard the edit.
 */
function removeMirror(dir, { force = false } = {}) {
  const side = readJson(path.join(dir, SIDECAR));
  if (!side || (!force && !stillOurs(dir))) return false;
  const src = side.source ? path.resolve(side.source) : null;
  for (const n of fs.readdirSync(dir)) {
    const p = path.join(dir, n);
    const st = lstat(p);
    if (st && st.isSymbolicLink() && (!src || inside(fs.readlinkSync(p), src))) fs.unlinkSync(p);
  }
  fs.rmSync(path.join(dir, 'SKILL.md'), { force: true });
  fs.rmSync(path.join(dir, SIDECAR), { force: true });
  try { fs.rmdirSync(dir); } catch { /* the user left something in it: keep the folder */ }
  return true;
}

function apply(actions, { now = new Date() } = {}) {
  const out = { written: [], removed: [], errors: [] };
  for (const a of actions) {
    try {
      if (a.type === 'mirror') { if (applyMirror(a, now)) out.written.push(a.id); }
      else if (a.type === 'remove') { if (removeMirror(a.dir)) out.removed.push(a.id); }
    } catch (e) {
      out.errors.push({ id: a.id, message: e.message });
    }
  }
  return out;
}

// ── cache ────────────────────────────────────────────────────────────────────

function cacheFile(vault) { return path.join(vault, 'brain', '_index', 'skills.json'); }

function readCache(file) {
  const c = readJson(file);
  return c && c.schema === SCHEMA && Array.isArray(c.skills) ? c : null;
}

function writeCache(file, cache) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  writeAtomic(file, `${JSON.stringify(cache, null, 2)}\n`);
}

// ── entry points ─────────────────────────────────────────────────────────────

/**
 * Discover, plan, apply (unless dryRun), and write the cache (unless dryRun). Returns { cache, actions, result }.
 * opts: { vault, userCfg, env, roots, now, dryRun }.
 */
function sync({ vault, userCfg = null, env = process.env, roots: r, now = new Date(), dryRun = false } = {}) {
  const R = r || roots({ userCfg, env });
  const hosts = hostsOf(userCfg);
  const config = skillsConfig({ vault, userCfg });
  const p = plan(discover(R), { roots: R, config, hosts });
  const result = dryRun ? { written: [], removed: [], errors: [] } : apply(p.actions, { now });
  const failed = new Map(result.errors.map((e) => [e.id, e.message]));
  for (const row of p.rows) {
    if (!failed.has(row.id)) continue;
    row.status = 'error';
    row.note = failed.get(row.id);
    for (const h of HOSTS) if (row.on[h] && row.on[h].via === 'mirror') row.on[h] = null;
  }
  const cache = {
    schema: SCHEMA,
    scannedAt: now.toISOString(),
    hosts: { claude: hosts.includes('claude'), codex: hosts.includes('codex') },
    sync: { on: p.sync.on, reason: p.sync.reason, at: dryRun ? null : now.toISOString(), written: result.written, removed: result.removed, errors: result.errors },
    skills: p.rows,
  };
  if (!dryRun && vault) writeCache(cacheFile(vault), cache);
  return { cache, actions: p.actions, result };
}

/** Delete an edited mirror so the next sync writes it fresh (`aos skills reset <name>`). */
function reset({ userCfg = null, env = process.env, roots: r, id }) {
  const R = r || roots({ userCfg, env });
  const want = String(id || '').toLowerCase();
  const found = discover(R);
  const removed = [];
  for (const m of [...found.claude.mirrors, ...found.codex.mirrors]) {
    if ((m.sidecar.id || idOf(m)) === want && removeMirror(m.dir, { force: true })) removed.push(m.dir);
  }
  return removed;
}

/** True for a folder a reader should skip: one of our mirrors (spec D8). */
function isMirrorDir(dir) { return fs.existsSync(path.join(dir, SIDECAR)); }

module.exports = {
  SCHEMA, SIDECAR, skillsConfig, hostsOf, roots, discover, plan, apply, sync, reset, isMirrorDir,
  cacheFile, readCache, writeCache, codexEnabledPlugins, codexPluginRoot,
};
