'use strict';
// Codex's own inventory for the HUD's System drawer (spec 2026-09-23-codex-parity-gaps D9).
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { codexCapabilities } = require('../collectors/capabilities.js');

test('codexCapabilities counts Codex skills (not aos-generated ones), prompts and hook entries; null when Codex is not a host', () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'caps-codex-'));
  const skills = fs.mkdtempSync(path.join(os.tmpdir(), 'caps-skills-'));
  fs.mkdirSync(path.join(skills, 'mine')); fs.writeFileSync(path.join(skills, 'mine', 'SKILL.md'), '---\nname: mine\n---\n');
  fs.mkdirSync(path.join(skills, 'wrap')); fs.writeFileSync(path.join(skills, 'wrap', 'SKILL.md'), '<!-- generated by `aos init --host codex` from the AgenticOS Workbench plugin -->\n');
  fs.mkdirSync(path.join(home, 'prompts')); fs.writeFileSync(path.join(home, 'prompts', 'review.md'), '# r\n');
  fs.writeFileSync(path.join(home, 'hooks.json'), JSON.stringify({ hooks: { Stop: [{ hooks: [{ type: 'command', command: 'a' }, { type: 'command', command: 'b' }] }], SessionStart: [{ hooks: [{ type: 'command', command: 'c' }] }] } }));
  const on = { hosts: { codex: { enabled: true } } };
  assert.deepEqual(codexCapabilities({ userConfig: on, codexHome: home, agentsSkillsDir: skills }), { skills: 1, prompts: 1, hooks: 3 });
  assert.equal(codexCapabilities({ userConfig: { hosts: { claude: { enabled: true } } }, codexHome: home, agentsSkillsDir: skills }), null);
  assert.equal(codexCapabilities({ userConfig: null, codexHome: home, agentsSkillsDir: skills }), null);
});

test('skill counts skip the mirrors lib/skills.js writes, on both hosts (spec 2026-09-23-universal-skills D8)', () => {
  const { collectCapabilities } = require('../collectors/capabilities.js');
  const mk = (dir, name, mirror) => {
    fs.mkdirSync(path.join(dir, name), { recursive: true });
    fs.writeFileSync(path.join(dir, name, 'SKILL.md'), `---\nname: ${name}\n---\n`);
    if (mirror) fs.writeFileSync(path.join(dir, name, '.aos-mirror.json'), '{"schema":1}');
  };
  const skills = fs.mkdtempSync(path.join(os.tmpdir(), 'caps-skills-'));
  mk(skills, 'mine', false); mk(skills, 'from-claude', true);
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'caps-codex-'));
  assert.equal(codexCapabilities({ userConfig: { hosts: { codex: { enabled: true } } }, codexHome: home, agentsSkillsDir: skills }).skills, 1);
  const cfg = fs.mkdtempSync(path.join(os.tmpdir(), 'caps-claude-'));
  mk(path.join(cfg, 'skills'), 'own', false); mk(path.join(cfg, 'skills'), 'from-codex', true);
  const caps = collectCapabilities({ claudeConfigDir: cfg, vault: fs.mkdtempSync(path.join(os.tmpdir(), 'caps-vault-')) });
  assert.equal(caps.skills.count, 1);
  assert.deepEqual(caps.skills.custom, ['own']);
});
