'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const S = require('../lib/skills.js');

const NOW = new Date('2026-09-23T12:00:00.000Z');
const BOTH = { hosts: { claude: { enabled: true }, codex: { enabled: true } } };
const CLAUDE_ONLY = { hosts: { claude: { enabled: true }, codex: { enabled: false } } };

/** A private world: a Claude config dir, a ~/.agents, a Codex home and a vault, all under one tmp dir. */
function world() {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), 'aos-skills-'));
  const r = {
    claudeSkills: path.join(base, 'claude', 'skills'),
    claudePlugins: path.join(base, 'claude', 'plugins', 'installed_plugins.json'),
    claudeSettings: path.join(base, 'claude', 'settings.json'),
    codexSkills: path.join(base, 'agents', 'skills'),
    codexSystem: path.join(base, 'codex', 'skills', '.system'),
    codexConfig: path.join(base, 'codex', 'config.toml'),
    codexPluginCache: path.join(base, 'codex', 'plugins', 'cache'),
  };
  const vault = path.join(base, 'vault');
  fs.mkdirSync(path.join(vault, 'brain', '_index'), { recursive: true });
  return { base, r, vault };
}

function skill(dir, text, extra = {}) {
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'SKILL.md'), text);
  for (const [rel, content] of Object.entries(extra)) {
    fs.mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true });
    fs.writeFileSync(path.join(dir, rel), content);
  }
  return dir;
}
const md = (name, desc, body = 'Body.\n') => `---\nname: ${name}\ndescription: ${desc}\n---\n\n${body}`;
const row = (cache, id) => cache.skills.find((s) => s.id === id);
const run = (w, userCfg = BOTH, extra = {}) => S.sync({ vault: w.vault, userCfg, roots: w.r, now: NOW, ...extra });

test('discover: user, synced, mirrors, plugins (enabled only, remote market dirs) and Codex built-ins', () => {
  const w = world();
  skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'Ship it'));
  skill(path.join(w.r.claudeSkills, 'synced', 'u1', 'pdf'), md('pdf', 'PDFs'));
  skill(path.join(w.r.codexSkills, 'triage'), md('triage', 'Triage'));
  skill(path.join(w.r.codexSkills, 'wrap'), `${md('wrap', 'Wrap')}<!-- generated by \`aos init --host codex\` from the AgenticOS Workbench plugin -->\n`);
  const cp = path.join(w.base, 'cp', 'frontend', '1.0.0');
  skill(path.join(cp, 'skills', 'frontend-design'), md('frontend-design', 'UI'));
  fs.mkdirSync(path.join(cp, 'commands'), { recursive: true });
  fs.writeFileSync(path.join(cp, 'commands', 'polish.md'), '---\ndescription: Polish\n---\nDo it\n');
  const off = path.join(w.base, 'cp', 'off', '1.0.0');
  skill(path.join(off, 'skills', 'hidden'), md('hidden', 'no'));
  fs.mkdirSync(path.dirname(w.r.claudePlugins), { recursive: true });
  fs.writeFileSync(w.r.claudePlugins, JSON.stringify({ version: 2, plugins: { 'frontend@m': [{ scope: 'user', installPath: cp }], 'off@m': [{ scope: 'user', installPath: off }] } }));
  fs.writeFileSync(w.r.claudeSettings, JSON.stringify({ enabledPlugins: { 'frontend@m': true, 'off@m': false } }));
  skill(path.join(w.r.codexPluginCache, 'openai-curated-remote', 'vercel', '0.2.0', 'skills', 'deploy-vercel'), md('deploy-vercel', 'Vercel'));
  skill(path.join(w.r.codexPluginCache, 'openai-curated', 'gone', '1', 'skills', 'nope'), md('nope', 'disabled'));
  fs.mkdirSync(path.dirname(w.r.codexConfig), { recursive: true });
  fs.writeFileSync(w.r.codexConfig, '[plugins."vercel@openai-curated"]\nenabled = true\n\n[plugins."gone@openai-curated"]\nenabled = false\n');
  skill(path.join(w.r.codexSystem, 'imagegen'), md('imagegen', 'Images'));

  const f = S.discover(w.r);
  assert.deepEqual(f.claude.user.map((s) => s.folder), ['deploy']);
  assert.deepEqual(f.claude.synced.map((s) => s.folder), ['pdf']);
  assert.deepEqual(f.codex.user.map((s) => s.folder), ['triage']);
  const listed = f.listed.map((l) => `${l.host}:${l.scope}:${l.plugin}:${l.name}:${l.invoke}`).sort();
  assert.deepEqual(listed, [
    'claude:plugin:frontend:frontend-design:/frontend:frontend-design',
    'claude:plugin:frontend:polish:/frontend:polish',
    'codex:builtin:null:imagegen:$imagegen',
    'codex:plugin:agenticos:wrap:$wrap',
    'codex:plugin:vercel:deploy-vercel:$vercel:deploy-vercel',
  ]);
});

test('codexEnabledPlugins: sections with enabled not false; other tables end a section', () => {
  const toml = '[plugins."a@m"]\nenabled = true\n[plugins."b@m"]\nenabled = false\n[plugins."c@m"]\n[other]\nenabled = false\n';
  assert.deepEqual(S.codexEnabledPlugins(toml), [{ plugin: 'a', market: 'm' }, { plugin: 'c', market: 'm' }]);
});

test('sync: mirrors both ways, translated, with symlinked supporting files and a sidecar; a second run is a no-op', () => {
  const w = world();
  const src = skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'Ship it', 'Deploy $ARGUMENTS, then /triage.\n'), { 'scripts/go.sh': 'echo go\n' });
  skill(path.join(w.r.codexSkills, 'triage'), md('triage', 'Triage', 'Then call $deploy.\n'));

  const { cache, result } = run(w);
  assert.deepEqual(result, { written: ['deploy', 'triage'], removed: [], errors: [] });
  const cx = path.join(w.r.codexSkills, 'deploy');
  const text = fs.readFileSync(path.join(cx, 'SKILL.md'), 'utf8');
  assert.match(text, /^---\nname: deploy\ndescription: Ship it\n---/);
  assert.match(text, /Deploy the text the user wrote after `\$deploy`, then \$triage\./);
  assert.equal(fs.readlinkSync(path.join(cx, 'scripts')), path.join(src, 'scripts'));
  const side = JSON.parse(fs.readFileSync(path.join(cx, S.SIDECAR), 'utf8'));
  assert.equal(side.schema, 1); assert.equal(side.from, 'claude'); assert.equal(side.source, src); assert.equal(side.id, 'deploy');
  assert.match(fs.readFileSync(path.join(w.r.claudeSkills, 'triage', 'SKILL.md'), 'utf8'), /Then call \/deploy\./);

  assert.equal(cache.sync.on, true);
  const d = row(cache, 'deploy');
  assert.equal(d.status, 'universal');
  assert.deepEqual(d.origin, { host: 'claude', scope: 'user', plugin: null, path: path.join(src, 'SKILL.md') });
  assert.equal(d.on.claude.invoke, '/deploy'); assert.equal(d.on.claude.via, 'native');
  assert.equal(d.on.codex.invoke, '$deploy'); assert.equal(d.on.codex.via, 'mirror');
  assert.equal(row(cache, 'triage').on.claude.invoke, '/triage');
  assert.deepEqual(JSON.parse(fs.readFileSync(S.cacheFile(w.vault), 'utf8')).skills.length, 2);

  // The mirrors are not re-read as native skills, and nothing changes the second time.
  const again = run(w);
  assert.deepEqual(again.result, { written: [], removed: [], errors: [] });
  assert.equal(again.cache.skills.length, 2);
});

test('sync: a changed source rewrites its mirror; a new supporting file gets a link; a gone one loses it', () => {
  const w = world();
  const src = skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'v1'), { 'a.md': 'a' });
  run(w);
  fs.writeFileSync(path.join(src, 'SKILL.md'), md('deploy', 'v2'));
  fs.rmSync(path.join(src, 'a.md'));
  fs.writeFileSync(path.join(src, 'b.md'), 'b');
  const { result } = run(w);
  assert.deepEqual(result.written, ['deploy']);
  const cx = path.join(w.r.codexSkills, 'deploy');
  assert.match(fs.readFileSync(path.join(cx, 'SKILL.md'), 'utf8'), /description: v2/);
  assert.equal(fs.existsSync(path.join(cx, 'a.md')), false);
  assert.equal(fs.readlinkSync(path.join(cx, 'b.md')), path.join(src, 'b.md'));
});

test('sync: an edited mirror is kept and flagged; reset discards the edit and the next sync rewrites it', () => {
  const w = world();
  skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'Ship'));
  run(w);
  const mirror = path.join(w.r.codexSkills, 'deploy', 'SKILL.md');
  fs.appendFileSync(mirror, 'my codex tweak\n');
  const { cache, result } = run(w);
  assert.deepEqual(result.written, []);
  assert.equal(row(cache, 'deploy').status, 'edited');
  assert.match(row(cache, 'deploy').note, /aos skills reset deploy/);
  assert.match(fs.readFileSync(mirror, 'utf8'), /my codex tweak/);

  assert.deepEqual(S.reset({ roots: w.r, id: 'deploy' }), [path.join(w.r.codexSkills, 'deploy')]);
  assert.equal(fs.existsSync(path.join(w.r.codexSkills, 'deploy')), false);
  assert.equal(row(run(w).cache, 'deploy').status, 'universal');
  assert.doesNotMatch(fs.readFileSync(mirror, 'utf8'), /my codex tweak/);
});

test('sync: a removed source takes its clean mirror; an edited orphan stays, and user files in a mirror survive', () => {
  const w = world();
  const a = skill(path.join(w.r.claudeSkills, 'a'), md('a', 'A'), { 'ref.md': 'r' });
  const b = skill(path.join(w.r.claudeSkills, 'b'), md('b', 'B'));
  run(w);
  fs.writeFileSync(path.join(w.r.codexSkills, 'a', 'notes.txt'), 'mine');
  fs.appendFileSync(path.join(w.r.codexSkills, 'b', 'SKILL.md'), 'edited\n');
  fs.rmSync(a, { recursive: true }); fs.rmSync(b, { recursive: true });
  const { cache, result } = run(w);
  assert.deepEqual(result.removed, ['a']);
  assert.deepEqual(fs.readdirSync(path.join(w.r.codexSkills, 'a')), ['notes.txt']);
  assert.equal(row(cache, 'a'), undefined);
  const orphan = row(cache, 'b');
  assert.equal(orphan.status, 'edited');
  assert.equal(orphan.origin.scope, 'mirror');
  assert.match(orphan.note, /source was removed/);
  assert.ok(fs.existsSync(path.join(w.r.codexSkills, 'b', 'SKILL.md')));
});

test('sync: native on both (same → universal, different → differs), a foreign folder in the way, no writes', () => {
  const w = world();
  skill(path.join(w.r.claudeSkills, 'same'), md('same', 'S'));
  skill(path.join(w.r.codexSkills, 'same'), md('same', 'S'));
  skill(path.join(w.r.claudeSkills, 'diff'), md('diff', 'one'));
  skill(path.join(w.r.codexSkills, 'diff'), md('diff', 'two'));
  skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'D'));
  skill(path.join(w.r.codexSkills, 'deploy'), md('ship', 'a Codex skill named ship in a folder named deploy'));
  const { cache, result } = run(w);
  assert.deepEqual(result.written, ['ship']);
  assert.equal(row(cache, 'same').status, 'universal');
  assert.equal(row(cache, 'same').on.codex.via, 'native');
  assert.equal(row(cache, 'diff').status, 'differs');
  assert.equal(row(cache, 'deploy').status, 'differs');
  assert.match(row(cache, 'deploy').note, /is not an AgenticOS mirror/);
  assert.match(fs.readFileSync(path.join(w.r.codexSkills, 'deploy', 'SKILL.md'), 'utf8'), /named ship/);
});

test('sync: excluded skills are not shared (a clean mirror goes); invalid ones are reported, not written', () => {
  const w = world();
  skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'D'));
  skill(path.join(w.r.claudeSkills, 'broken'), '/a/path/only\n');
  run(w);
  assert.ok(fs.existsSync(path.join(w.r.codexSkills, 'deploy')));
  fs.writeFileSync(path.join(w.vault, 'brain', 'config.json'), JSON.stringify({ skills: { exclude: ['Deploy'] } }));
  const { cache, result } = run(w);
  assert.deepEqual(result.removed, ['deploy']);
  assert.equal(row(cache, 'deploy').status, 'excluded');
  assert.equal(row(cache, 'deploy').on.codex, null);
  assert.equal(row(cache, 'broken').status, 'invalid');
  assert.match(row(cache, 'broken').note, /no YAML frontmatter/);
  assert.equal(fs.existsSync(path.join(w.r.codexSkills, 'broken')), false);
});

test('sync: one host enabled, or skills.sync false → list only, with the reason', () => {
  const w = world();
  skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'D'));
  const one = run(w, CLAUDE_ONLY);
  assert.equal(one.cache.sync.on, false);
  assert.equal(one.cache.sync.reason, 'sharing needs both hosts enabled');
  assert.deepEqual(one.cache.hosts, { claude: true, codex: false });
  assert.equal(row(one.cache, 'deploy').status, 'pending');
  assert.equal(fs.existsSync(w.r.codexSkills), false);
  const legacy = run(w, {});
  assert.deepEqual(legacy.cache.hosts, { claude: true, codex: false });
  const off = run(w, { ...BOTH, skills: { sync: false } });
  assert.equal(off.cache.sync.reason, 'sharing is off (skills.sync is false)');
  assert.equal(fs.existsSync(w.r.codexSkills), false);
});

test('sync: dryRun plans without writing mirrors or the cache', () => {
  const w = world();
  skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'D'));
  const { actions } = run(w, BOTH, { dryRun: true });
  assert.deepEqual(actions.map((a) => `${a.type}:${a.id}`), ['mirror:deploy']);
  assert.equal(fs.existsSync(w.r.codexSkills), false);
  assert.equal(fs.existsSync(S.cacheFile(w.vault)), false);
});

test('sync: a plugin skill both hosts ship is one listed row, and user skills refer to it in the target form', () => {
  const w = world();
  const cp = path.join(w.base, 'cp', 'agenticos', '0.13.0');
  fs.mkdirSync(path.join(cp, 'commands'), { recursive: true });
  fs.writeFileSync(path.join(cp, 'commands', 'wrap.md'), '---\ndescription: Wrap\n---\nwrap\n');
  fs.mkdirSync(path.dirname(w.r.claudePlugins), { recursive: true });
  fs.writeFileSync(w.r.claudePlugins, JSON.stringify({ version: 2, plugins: { 'agenticos@agenticos-workbench': [{ installPath: cp }] } }));
  skill(path.join(w.r.codexPluginCache, 'agenticos-workbench', 'agenticos', '0.13.0', 'skills', 'wrap'), md('wrap', 'Wrap'));
  fs.mkdirSync(path.dirname(w.r.codexConfig), { recursive: true });
  fs.writeFileSync(w.r.codexConfig, '[plugins."agenticos@agenticos-workbench"]\nenabled = true\n');
  skill(path.join(w.r.claudeSkills, 'close'), md('close', 'Close out', 'Run /wrap, or /agenticos:wrap.\n'));
  const { cache } = run(w);
  const wrap = row(cache, 'agenticos:wrap');
  assert.equal(wrap.status, 'listed');
  assert.equal(wrap.on.claude.invoke, '/agenticos:wrap');
  assert.equal(wrap.on.codex.invoke, '$agenticos:wrap');
  assert.match(fs.readFileSync(path.join(w.r.codexSkills, 'close', 'SKILL.md'), 'utf8'), /Run \$agenticos:wrap, or \$agenticos:wrap\./);
});

test('isMirrorDir: true only for a folder with the sidecar', () => {
  const w = world();
  skill(path.join(w.r.claudeSkills, 'deploy'), md('deploy', 'D'));
  run(w);
  assert.equal(S.isMirrorDir(path.join(w.r.codexSkills, 'deploy')), true);
  assert.equal(S.isMirrorDir(path.join(w.r.claudeSkills, 'deploy')), false);
});
