'use strict';
const { test } = require('node:test');
const assert = require('node:assert');
const path = require('path');
const { parseManifest } = require('../collectors/workspaces');

const FIXTURES = path.join(__dirname, 'fixtures');

test('parseManifest reads scalars, objective list, and mixed subprojects', () => {
  const fs = require('fs');
  const text = fs.readFileSync(path.join(FIXTURES, 'full-manifest', 'workspace.md'), 'utf8');
  const m = parseManifest(text);
  assert.equal(m.status, 'active');
  assert.equal(m.summary, 'Ship the onboarding skill');
  assert.deepEqual(m.objectives, ['Ship onboarding (P0)', 'QA 3 platform skills']);
  assert.deepEqual(m.subprojects, [
    { name: 'factory', path: 'factory' },
    { name: 'research', path: 'research' },
  ]);
  assert.equal(m.next, 'Finish QA on the reporting dashboard');
});

test('parseManifest returns empty shape when no frontmatter', () => {
  const m = parseManifest('# just a heading\nno frontmatter here');
  assert.deepEqual(m, { status: null, summary: null, objectives: [], subprojects: [], documents: [], next: null });
});

const { detectChildren } = require('../collectors/workspaces');

test('detectChildren flags a collection and excludes noise dirs', () => {
  const abs = path.join(FIXTURES, 'collection');
  const res = detectChildren(abs, 'workspaces/collection');
  assert.equal(res.isCollection, true);
  const names = res.subprojects.map(s => s.name).sort();
  assert.deepEqual(names, ['ProjectA', 'ProjectB']);
  assert.ok(!names.includes('node_modules'));
  assert.equal(res.docs.length, 0);
});

test('detectChildren treats single-project as docs, not subprojects', () => {
  const abs = path.join(FIXTURES, 'single-project');
  const res = detectChildren(abs, 'workspaces/single-project');
  assert.equal(res.isCollection, false);
  assert.equal(res.subprojects.length, 0);
  assert.deepEqual(res.docs.map(d => d.name), ['STATUS.md']);
});

const { extractObjectives, collectWorkspaces, computeInputHash } = require('../collectors/workspaces');

test('extractObjectives pulls bullets under an Objectives/Goals heading', () => {
  const md = '# Title\n\n## Objectives\n- First goal\n- Second goal\n\n## Other\n- not this';
  assert.deepEqual(extractObjectives(md), ['First goal', 'Second goal']);
});

test('collectWorkspaces builds entries with correct provenance', () => {
  const list = collectWorkspaces({ vault: __dirname, workspacesDirName: 'fixtures' });
  const byName = Object.fromEntries(list.map(w => [w.name, w]));

  const full = byName['full-manifest'];
  assert.equal(full.status, 'active');
  assert.equal(full.statusSource, 'manifest');
  assert.equal(full.summary, 'Ship the onboarding skill');
  assert.equal(full.summarySource, 'manifest');
  assert.equal(full.objectives[0].source, 'manifest');
  assert.equal(full.isCollection, false); // manifest subprojects present
  assert.deepEqual(full.subprojects.map(s => s.name), ['factory', 'research']);
  assert.equal(full.next.text, 'Finish QA on the reporting dashboard');

  const coll = byName['collection'];
  assert.equal(coll.isCollection, true);
  assert.deepEqual(coll.subprojects.map(s => s.name), ['ProjectA', 'ProjectB']);

  const single = byName['single-project'];
  assert.equal(single.isCollection, false);
  assert.equal(single.docs[0].name, 'STATUS.md');
  // no insight is generated by the sync collector
  assert.equal(single.insight.status, 'unavailable');
  assert.equal(single.insight.text, null);
});

test('extractObjectives also reads Scope / Project Scope headings', () => {
  const md = '# Title\n\n## Project Scope\n- Draft the thing\n- Review it\n\n## Other\n- not this';
  assert.deepEqual(extractObjectives(md), ['Draft the thing', 'Review it']);
  const bare = '# Title\n\n## Scope\n- Only this\n\n## Other\n- not this';
  assert.deepEqual(extractObjectives(bare), ['Only this']);
});

test('summary falls back to CLAUDE.md first body line', () => {
  const list = collectWorkspaces({ vault: __dirname, workspacesDirName: 'fixtures' });
  const w = list.find((x) => x.name === 'claude-only');
  assert.equal(w.summary, 'This workspace only has a CLAUDE.md and nothing else.');
  assert.equal(w.summarySource, 'derived');
  assert.deepEqual(w.objectives.map((o) => o.text), ['Draft the thing', 'Review the other thing']);
  assert.equal(w.objectives[0].source, 'derived');
  assert.equal(w.next.text, 'Ship the draft for review');
  assert.equal(w.next.source, 'derived');
  assert.ok(['active', 'idle', 'planned'].includes(w.status));
  assert.equal(w.statusSource, 'derived');
});

test('next falls through to derived (git subject) when no Next heading exists', () => {
  const list = collectWorkspaces({ vault: __dirname, workspacesDirName: 'fixtures' });
  const w = list.find((x) => x.name === 'no-next');
  // STATUS.md has no Next/TODO heading, so extractNext yields nothing and the
  // derivation takes the git-subject fallback branch. Source is always derived;
  // text is the commit subject (string) once the fixture is committed, else null.
  assert.equal(w.next.source, 'derived');
  assert.ok(w.next.text === null || typeof w.next.text === 'string');
});

test('computeInputHash is stable for equal inputs and changes on edit', () => {
  const base = { status: 'active', summary: 's', objectives: [{ text: 'a' }], subprojects: [{ name: 'x', status: null }], next: { text: 'n' }, lastEvent: { ageDays: 1 } };
  const h1 = computeInputHash(base);
  const h2 = computeInputHash(JSON.parse(JSON.stringify(base)));
  assert.equal(h1, h2);
  const changed = { ...base, summary: 'different' };
  assert.notEqual(h1, computeInputHash(changed));
});

const { extractNext } = require('../collectors/workspaces');

test('extractNext reads the first bullet under Next / What\'s Next / TODO', () => {
  assert.equal(extractNext('## Next\n- Do the first thing\n- second'), 'Do the first thing');
  assert.equal(extractNext("### What's Next\n- Ship it"), 'Ship it');
  assert.equal(extractNext("## What’s Next\n- Smart-quoted"), 'Smart-quoted');
  assert.equal(extractNext('## TODO\n- Fix the bug'), 'Fix the bug');
  assert.equal(extractNext('# Title\nno next section here'), null);
});

const { defaultStatusFromAge } = require('../collectors/workspaces');

test('defaultStatusFromAge buckets by recency (14d active / 60d idle)', () => {
  assert.equal(defaultStatusFromAge(5), 'active');
  assert.equal(defaultStatusFromAge(14), 'active');
  assert.equal(defaultStatusFromAge(30), 'idle');
  assert.equal(defaultStatusFromAge(60), 'idle');
  assert.equal(defaultStatusFromAge(90), 'planned');
  assert.equal(defaultStatusFromAge(null), 'planned');
});
